/**
 * @file ICodeSandbox.ts
 * @description Interface for the Code Execution Sandbox in AgentOS.
 *
 * The sandbox provides isolated execution environments for running
 * code generated by agents. It supports multiple languages and includes
 * security controls to prevent harmful operations.
 *
 * @module AgentOS/Sandbox
 * @version 1.0.0
 */

import type { ILogger } from '../../logging/ILogger';

// ============================================================================
// Types
// ============================================================================

/**
 * Supported programming languages for code execution.
 */
export type SandboxLanguage = 'python' | 'javascript' | 'typescript' | 'shell' | 'sql';

/**
 * Status of sandbox execution.
 */
export type ExecutionStatus = 'pending' | 'running' | 'success' | 'error' | 'timeout' | 'killed';

/**
 * Configuration for the sandbox environment.
 */
export interface SandboxConfig {
  /** Maximum execution time in milliseconds */
  timeoutMs?: number;
  /** Maximum memory in bytes */
  maxMemoryBytes?: number;
  /** Maximum output size in bytes */
  maxOutputBytes?: number;
  /** Environment variables to inject */
  envVars?: Record<string, string>;
  /** Working directory for execution */
  workingDir?: string;
  /** Whether to allow network access */
  allowNetwork?: boolean;
  /** Whether to allow filesystem access */
  allowFilesystem?: boolean;
  /** Allowed filesystem paths (if allowFilesystem is true) */
  allowedPaths?: string[];
  /** Blocked imports/modules */
  blockedModules?: string[];
  /** Maximum CPU time in milliseconds */
  maxCpuTimeMs?: number;
}

/**
 * Input files to provide to the sandbox.
 */
export interface SandboxFile {
  /** File path relative to working directory */
  path: string;
  /** File content */
  content: string;
  /** File encoding */
  encoding?: 'utf8' | 'base64' | 'binary';
}

/**
 * Request to execute code in the sandbox.
 */
export interface ExecutionRequest {
  /** Unique execution ID */
  executionId?: string;
  /** Programming language */
  language: SandboxLanguage;
  /** Code to execute */
  code: string;
  /** Input data (stdin) */
  stdin?: string;
  /** Command-line arguments */
  args?: string[];
  /** Input files */
  files?: SandboxFile[];
  /** Sandbox configuration overrides */
  config?: Partial<SandboxConfig>;
  /** Metadata for tracking */
  metadata?: Record<string, unknown>;
}

/**
 * Output from sandbox execution.
 */
export interface ExecutionOutput {
  /** Standard output */
  stdout: string;
  /** Standard error */
  stderr: string;
  /** Exit code */
  exitCode: number;
  /** Output files generated */
  files?: SandboxFile[];
}

/**
 * Result of code execution.
 */
export interface ExecutionResult {
  /** Unique execution ID */
  executionId: string;
  /** Execution status */
  status: ExecutionStatus;
  /** Output from execution */
  output?: ExecutionOutput;
  /** Error message if execution failed */
  error?: string;
  /** Execution duration in milliseconds */
  durationMs: number;
  /** Memory used in bytes */
  memoryUsedBytes?: number;
  /** CPU time used in milliseconds */
  cpuTimeMs?: number;
  /** Timestamp when execution started */
  startedAt: string;
  /** Timestamp when execution completed */
  completedAt: string;
  /** Whether execution was truncated due to limits */
  truncated?: {
    stdout?: boolean;
    stderr?: boolean;
    timeout?: boolean;
  };
  /** Security events detected */
  securityEvents?: SecurityEvent[];
}

/**
 * Security event detected during execution.
 */
export interface SecurityEvent {
  /** Event type */
  type: 'blocked_import' | 'blocked_syscall' | 'network_attempt' | 'filesystem_violation' | 'resource_limit';
  /** Description of the event */
  description: string;
  /** Timestamp */
  timestamp: string;
  /** Severity */
  severity: 'low' | 'medium' | 'high' | 'critical';
}

/**
 * Statistics about sandbox usage.
 */
export interface SandboxStats {
  /** Total executions */
  totalExecutions: number;
  /** Successful executions */
  successfulExecutions: number;
  /** Failed executions */
  failedExecutions: number;
  /** Timed out executions */
  timedOutExecutions: number;
  /** Killed executions */
  killedExecutions: number;
  /** Average execution time */
  avgDurationMs: number;
  /** Average memory usage */
  avgMemoryBytes: number;
  /** Executions by language */
  byLanguage: Record<SandboxLanguage, number>;
  /** Security events count */
  securityEventsCount: number;
}

// ============================================================================
// Interface
// ============================================================================

/**
 * Interface for the Code Execution Sandbox.
 *
 * @example
 * ```typescript
 * const sandbox = new CodeSandbox();
 *
 * const result = await sandbox.execute({
 *   language: 'python',
 *   code: `
 *     import json
 *     data = {"result": 42}
 *     print(json.dumps(data))
 *   `,
 * });
 *
 * console.log(result.output?.stdout); // '{"result": 42}'
 * ```
 */
export interface ICodeSandbox {
  /**
   * Initializes the sandbox.
   * @param logger - Logger instance
   * @param defaultConfig - Default configuration
   */
  initialize(logger?: ILogger, defaultConfig?: SandboxConfig): Promise<void>;

  /**
   * Executes code in the sandbox.
   * @param request - Execution request
   * @returns Execution result
   */
  execute(request: ExecutionRequest): Promise<ExecutionResult>;

  /**
   * Kills a running execution.
   * @param executionId - ID of the execution to kill
   * @returns Whether the kill was successful
   */
  kill(executionId: string): Promise<boolean>;

  /**
   * Gets the status of an execution.
   * @param executionId - ID of the execution
   * @returns Current execution result or undefined
   */
  getExecution(executionId: string): Promise<ExecutionResult | undefined>;

  /**
   * Lists recent executions.
   * @param limit - Maximum number to return
   * @returns Array of execution results
   */
  listExecutions(limit?: number): Promise<ExecutionResult[]>;

  /**
   * Checks if a language is supported.
   * @param language - Language to check
   * @returns Whether the language is supported
   */
  isLanguageSupported(language: string): boolean;

  /**
   * Gets supported languages.
   * @returns Array of supported languages
   */
  getSupportedLanguages(): SandboxLanguage[];

  /**
   * Gets sandbox statistics.
   * @returns Current statistics
   */
  getStats(): SandboxStats;

  /**
   * Resets statistics.
   */
  resetStats(): void;

  /**
   * Validates code for obvious security issues.
   * @param language - Programming language
   * @param code - Code to validate
   * @returns Array of security concerns
   */
  validateCode(language: SandboxLanguage, code: string): SecurityEvent[];

  /**
   * Disposes of the sandbox and cleans up resources.
   */
  dispose(): Promise<void>;
}

/**
 * Error thrown when sandbox execution fails.
 */
export class SandboxError extends Error {
  public readonly executionId?: string;
  public readonly status: ExecutionStatus;
  public readonly securityEvents?: SecurityEvent[];

  constructor(
    message: string,
    status: ExecutionStatus,
    executionId?: string,
    securityEvents?: SecurityEvent[],
  ) {
    super(message);
    this.name = 'SandboxError';
    this.executionId = executionId;
    this.status = status;
    this.securityEvents = securityEvents;
  }
}



