/**
 * StrandInsightsCard - Context-aware insights for selected strand
 *
 * Displays rich metadata and insights about the currently selected strand
 * including difficulty, tags, relationships, quality checks, and stats.
 *
 * @module codex/ui/StrandInsightsCard
 */

'use client'

import React, { useState, useMemo } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  FileText,
  Folder,
  StickyNote,
  Zap,
  Tag,
  Link2,
  CheckCircle2,
  XCircle,
  Clock,
  Calendar,
  ChevronDown,
  ChevronRight,
  BookOpen,
  Brain,
  Sparkles,
  AlertCircle,
} from 'lucide-react'
import type { StrandMetadata } from '../../types'

interface StrandInsightsCardProps {
  /** Strand metadata */
  metadata: StrandMetadata | null
  /** File content for word count */
  content?: string
  /** File name (fallback for title) */
  fileName?: string
  /** Current theme */
  theme?: string
}

// Difficulty level colors
const DIFFICULTY_COLORS: Record<string, { bg: string; text: string; bar: string }> = {
  beginner: { bg: 'bg-emerald-100 dark:bg-emerald-900/30', text: 'text-emerald-700 dark:text-emerald-400', bar: 'bg-emerald-500' },
  intermediate: { bg: 'bg-amber-100 dark:bg-amber-900/30', text: 'text-amber-700 dark:text-amber-400', bar: 'bg-amber-500' },
  advanced: { bg: 'bg-orange-100 dark:bg-orange-900/30', text: 'text-orange-700 dark:text-orange-400', bar: 'bg-orange-500' },
  expert: { bg: 'bg-red-100 dark:bg-red-900/30', text: 'text-red-700 dark:text-red-400', bar: 'bg-red-500' },
}

// Strand type icons
const TYPE_ICONS: Record<string, React.FC<{ className?: string }>> = {
  file: FileText,
  folder: Folder,
  supernote: StickyNote,
}

// Maturity status labels
const MATURITY_LABELS: Record<string, { label: string; color: string }> = {
  fleeting: { label: 'Fleeting', color: 'text-zinc-500' },
  literature: { label: 'Literature', color: 'text-blue-500' },
  permanent: { label: 'Permanent', color: 'text-emerald-500' },
  evergreen: { label: 'Evergreen', color: 'text-green-600' },
}

export default function StrandInsightsCard({
  metadata,
  content,
  fileName,
  theme = 'light',
}: StrandInsightsCardProps) {
  const [showAllTags, setShowAllTags] = useState(false)
  const [showQualityDetails, setShowQualityDetails] = useState(false)

  const isDark = theme?.includes('dark')

  // Calculate word count and reading time
  const { wordCount, readingTime } = useMemo(() => {
    if (!content) return { wordCount: 0, readingTime: 0 }
    const words = content.trim().split(/\s+/).filter(Boolean).length
    const minutes = Math.ceil(words / 200) // ~200 wpm average
    return { wordCount: words, readingTime: minutes }
  }, [content])

  // Get tags as array
  const tags = useMemo(() => {
    if (!metadata?.tags) return []
    return Array.isArray(metadata.tags) ? metadata.tags : [metadata.tags]
  }, [metadata?.tags])

  // Calculate quality score
  const qualityScore = useMemo(() => {
    if (!metadata?.qualityChecks) return null
    const checks = metadata.qualityChecks
    const total = Object.keys(checks).length
    const passed = Object.values(checks).filter(Boolean).length
    return { passed, total, percent: Math.round((passed / total) * 100) }
  }, [metadata?.qualityChecks])

  // Get relationships count
  const relationshipsCount = useMemo(() => {
    if (!metadata?.relationships) return { references: 0, prerequisites: 0, seeAlso: 0 }
    return {
      references: metadata.relationships.references?.length ?? 0,
      prerequisites: metadata.relationships.prerequisites?.length ?? 0,
      seeAlso: metadata.relationships.seeAlso?.length ?? 0,
    }
  }, [metadata?.relationships])

  const totalRelationships = relationshipsCount.references + relationshipsCount.prerequisites + relationshipsCount.seeAlso

  // Get difficulty info
  const difficultyInfo = useMemo(() => {
    if (!metadata?.difficulty) return null
    const difficulty = typeof metadata.difficulty === 'string'
      ? metadata.difficulty
      : metadata.difficulty.overall ?? 'intermediate'
    return {
      level: difficulty,
      colors: DIFFICULTY_COLORS[difficulty] ?? DIFFICULTY_COLORS.intermediate,
    }
  }, [metadata?.difficulty])

  // Get strand type
  const strandType = metadata?.strandType ?? 'file'
  const TypeIcon = TYPE_ICONS[strandType] ?? FileText

  // Get title
  const title = metadata?.title ?? fileName ?? 'Untitled'

  // Format last updated
  const lastUpdated = useMemo(() => {
    const date = metadata?.publishing?.lastUpdated ?? metadata?.autoGenerated?.lastIndexed
    if (!date) return null
    const d = new Date(date)
    const now = new Date()
    const diffDays = Math.floor((now.getTime() - d.getTime()) / (1000 * 60 * 60 * 24))
    if (diffDays === 0) return 'Today'
    if (diffDays === 1) return 'Yesterday'
    if (diffDays < 7) return `${diffDays} days ago`
    if (diffDays < 30) return `${Math.floor(diffDays / 7)} weeks ago`
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
  }, [metadata?.publishing?.lastUpdated, metadata?.autoGenerated?.lastIndexed])

  // No metadata - show placeholder
  if (!metadata) {
    return (
      <div className={`p-4 rounded-xl border ${isDark ? 'border-zinc-700 bg-zinc-800/50' : 'border-zinc-200 bg-zinc-50'}`}>
        <div className="flex items-center gap-2 text-zinc-400">
          <AlertCircle className="w-4 h-4" />
          <span className="text-sm">No metadata available</span>
        </div>
      </div>
    )
  }

  return (
    <div className={`rounded-xl border overflow-hidden ${isDark ? 'border-zinc-700 bg-zinc-800/30' : 'border-zinc-200 bg-white'}`}>
      {/* Header - Title + Type */}
      <div className={`px-3 py-2.5 border-b ${isDark ? 'border-zinc-700 bg-zinc-800/50' : 'border-zinc-100 bg-zinc-50'}`}>
        <div className="flex items-start gap-2">
          <TypeIcon className={`w-4 h-4 mt-0.5 flex-shrink-0 ${isDark ? 'text-zinc-400' : 'text-zinc-500'}`} />
          <div className="flex-1 min-w-0">
            <h4 className={`text-sm font-semibold truncate ${isDark ? 'text-zinc-100' : 'text-zinc-900'}`}>
              {title}
            </h4>
            <div className="flex items-center gap-2 mt-0.5">
              <span className={`text-[10px] px-1.5 py-0.5 rounded font-medium ${isDark ? 'bg-zinc-700 text-zinc-300' : 'bg-zinc-200 text-zinc-600'}`}>
                {strandType}
              </span>
              {metadata?.maturity?.status && (
                <span className={`text-[10px] font-medium ${MATURITY_LABELS[metadata.maturity.status]?.color ?? 'text-zinc-500'}`}>
                  {MATURITY_LABELS[metadata.maturity.status]?.label ?? metadata.maturity.status}
                </span>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="p-3 space-y-3">
        {/* Difficulty + Content Type */}
        {(difficultyInfo || metadata?.contentType) && (
          <div className="flex flex-wrap items-center gap-2">
            {difficultyInfo && (
              <div className={`flex items-center gap-1.5 px-2 py-1 rounded-md text-[10px] font-medium ${difficultyInfo.colors.bg} ${difficultyInfo.colors.text}`}>
                <Zap className="w-3 h-3" />
                <span className="capitalize">{difficultyInfo.level}</span>
              </div>
            )}
            {metadata?.contentType && (
              <div className={`px-2 py-1 rounded-md text-[10px] font-medium ${isDark ? 'bg-blue-900/30 text-blue-400' : 'bg-blue-100 text-blue-700'}`}>
                <BookOpen className="w-3 h-3 inline mr-1" />
                {metadata.contentType}
              </div>
            )}
          </div>
        )}

        {/* Tags */}
        {tags.length > 0 && (
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-1">
                <Tag className={`w-3 h-3 ${isDark ? 'text-cyan-400' : 'text-cyan-600'}`} />
                <span className={`text-[10px] font-medium ${isDark ? 'text-zinc-400' : 'text-zinc-500'}`}>
                  Tags ({tags.length})
                </span>
              </div>
              {tags.length > 5 && (
                <button
                  onClick={() => setShowAllTags(!showAllTags)}
                  className={`text-[9px] ${isDark ? 'text-cyan-400' : 'text-cyan-600'}`}
                >
                  {showAllTags ? 'Show less' : `+${tags.length - 5} more`}
                </button>
              )}
            </div>
            <div className="flex flex-wrap gap-1">
              {(showAllTags ? tags : tags.slice(0, 5)).map((tag, i) => (
                <span
                  key={`${tag}-${i}`}
                  className={`px-1.5 py-0.5 rounded text-[10px] ${isDark ? 'bg-zinc-700 text-zinc-300' : 'bg-zinc-100 text-zinc-600'}`}
                >
                  {tag}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Subjects & Topics */}
        {(metadata?.taxonomy?.subjects?.length || metadata?.taxonomy?.topics?.length) && (
          <div className="space-y-1.5">
            <div className="flex items-center gap-1">
              <Sparkles className={`w-3 h-3 ${isDark ? 'text-amber-400' : 'text-amber-600'}`} />
              <span className={`text-[10px] font-medium ${isDark ? 'text-zinc-400' : 'text-zinc-500'}`}>
                Classification
              </span>
            </div>
            <div className="flex flex-wrap gap-1">
              {metadata?.taxonomy?.subjects?.slice(0, 3).map((subject, i) => (
                <span
                  key={`subj-${i}`}
                  className={`px-1.5 py-0.5 rounded text-[10px] font-medium ${isDark ? 'bg-purple-900/30 text-purple-400' : 'bg-purple-100 text-purple-700'}`}
                >
                  {subject}
                </span>
              ))}
              {metadata?.taxonomy?.topics?.slice(0, 3).map((topic, i) => (
                <span
                  key={`topic-${i}`}
                  className={`px-1.5 py-0.5 rounded text-[10px] ${isDark ? 'bg-zinc-700 text-zinc-300' : 'bg-zinc-100 text-zinc-600'}`}
                >
                  {topic}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Relationships */}
        {totalRelationships > 0 && (
          <div className={`flex items-center gap-3 text-[10px] ${isDark ? 'text-zinc-400' : 'text-zinc-500'}`}>
            <Link2 className="w-3 h-3" />
            <span>
              {relationshipsCount.references > 0 && `${relationshipsCount.references} refs`}
              {relationshipsCount.prerequisites > 0 && ` • ${relationshipsCount.prerequisites} prereqs`}
              {relationshipsCount.seeAlso > 0 && ` • ${relationshipsCount.seeAlso} related`}
            </span>
          </div>
        )}

        {/* Quality Checks */}
        {qualityScore && (
          <div className="space-y-1.5">
            <button
              onClick={() => setShowQualityDetails(!showQualityDetails)}
              className={`w-full flex items-center justify-between text-[10px] ${isDark ? 'text-zinc-400' : 'text-zinc-500'}`}
            >
              <div className="flex items-center gap-1.5">
                <Brain className="w-3 h-3" />
                <span className="font-medium">Quality Checks</span>
                <span className={`px-1 py-0.5 rounded text-[9px] font-medium ${
                  qualityScore.percent >= 75 ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400' :
                  qualityScore.percent >= 50 ? 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400' :
                  'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400'
                }`}>
                  {qualityScore.passed}/{qualityScore.total}
                </span>
              </div>
              {showQualityDetails ? <ChevronDown className="w-3 h-3" /> : <ChevronRight className="w-3 h-3" />}
            </button>

            <AnimatePresence>
              {showQualityDetails && metadata?.qualityChecks && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: 'auto', opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  transition={{ duration: 0.15 }}
                  className="overflow-hidden"
                >
                  <div className={`space-y-1 pl-4 pt-1 ${isDark ? 'text-zinc-400' : 'text-zinc-500'}`}>
                    {Object.entries(metadata.qualityChecks).map(([key, value]) => (
                      <div key={key} className="flex items-center gap-1.5 text-[10px]">
                        {value ? (
                          <CheckCircle2 className="w-3 h-3 text-emerald-500" />
                        ) : (
                          <XCircle className="w-3 h-3 text-zinc-400" />
                        )}
                        <span className={value ? '' : 'opacity-60'}>
                          {key === 'hasContext' && 'Has context'}
                          {key === 'hasConnections' && 'Has connections'}
                          {key === 'isAtomic' && 'Atomic (single idea)'}
                          {key === 'isSelfContained' && 'Self-contained'}
                          {key === 'isVerified' && 'Verified'}
                          {key === 'hasSources' && 'Has sources'}
                        </span>
                      </div>
                    ))}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        )}

        {/* Stats Row */}
        <div className={`flex items-center justify-between pt-2 border-t text-[10px] ${isDark ? 'border-zinc-700 text-zinc-500' : 'border-zinc-100 text-zinc-400'}`}>
          <div className="flex items-center gap-3">
            {wordCount > 0 && (
              <span className="flex items-center gap-1">
                <FileText className="w-3 h-3" />
                {wordCount.toLocaleString()} words
              </span>
            )}
            {readingTime > 0 && (
              <span className="flex items-center gap-1">
                <Clock className="w-3 h-3" />
                ~{readingTime} min
              </span>
            )}
          </div>
          {lastUpdated && (
            <span className="flex items-center gap-1">
              <Calendar className="w-3 h-3" />
              {lastUpdated}
            </span>
          )}
        </div>

        {/* AI Summary if available */}
        {(metadata?.summary || metadata?.aiSummary || metadata?.autoGenerated?.summary) && (
          <div className={`pt-2 border-t ${isDark ? 'border-zinc-700' : 'border-zinc-100'}`}>
            <p className={`text-[11px] leading-relaxed line-clamp-3 ${isDark ? 'text-zinc-400' : 'text-zinc-500'}`}>
              {metadata?.aiSummary || metadata?.summary || metadata?.autoGenerated?.summary}
            </p>
          </div>
        )}
      </div>
    </div>
  )
}
