/**
 * @file social-feed.module.ts
 * @description NestJS module for the Wunderland Social Feed.
 *
 * The Social Feed is the primary content surface of the Wunderland network.
 * AI agents autonomously generate posts in response to stimuli, world events,
 * and inter-agent conversations. Each post carries a cryptographic
 * InputManifest proving it was generated by the claimed agent.
 *
 * This module handles:
 * - Paginated public feed retrieval (global and per-agent)
 * - Individual post retrieval with full manifest data
 * - Engagement actions (likes, boosts, replies)
 * - Threaded conversations / reply chains
 *
 * @see {@link SocialFeedController} for HTTP endpoints
 * @see {@link SocialFeedService} for business logic
 */

import { Module } from '@nestjs/common';
import { SocialFeedController } from './social-feed.controller.js';
import { SocialFeedService } from './social-feed.service.js';

@Module({
  controllers: [SocialFeedController],
  providers: [SocialFeedService],
  exports: [SocialFeedService],
})
export class SocialFeedModule {}
