// File: backend/agentos/api/types/AgentOSResponse.ts
/**
 * @fileoverview Defines the unified streaming output structure for the AgentOS API.
 * This interface allows for real-time delivery of text deltas, tool call requests,
 * system progress, and final comprehensive responses from the AgentOS.
 * @module backend/agentos/api/types/AgentOSResponse
 */

import {
  ToolCallRequest, // Ensure this is what IGMI.ts exports, as suggested by your comment
  AudioOutputConfig,
  ImageOutputConfig,
  UICommand,
  ReasoningTraceEntry as ReasoningTrace, // Assuming ReasoningTrace in IGMI is ReasoningTraceEntry[]
  CostAggregator,
} from '../../cognitive_substrate/IGMI';
import { ConversationContext } from '../../core/conversation/ConversationContext';
import { IPersonaDefinition } from '../../cognitive_substrate/personas/IPersonaDefinition';
import type { WorkflowProgressUpdate } from '../../core/workflows/WorkflowTypes';

/**
 * @enum {string} AgentOSResponseChunkType
 * Defines the distinct types of chunks that can be streamed from the AgentOS.
 */
export enum AgentOSResponseChunkType {
  TEXT_DELTA = 'text_delta',
  SYSTEM_PROGRESS = 'system_progress',
  TOOL_CALL_REQUEST = 'tool_call_request',
  TOOL_RESULT_EMISSION = 'tool_result_emission',
  UI_COMMAND = 'ui_command',
  FINAL_RESPONSE = 'final_response',
  ERROR = 'error',
  METADATA_UPDATE = 'metadata_update',
  WORKFLOW_UPDATE = 'workflow_update',
  AGENCY_UPDATE = 'agency_update',
  PROVENANCE_EVENT = 'provenance_event',
}

/**
 * @typedef {Object} AgentOSResponseChunk
 * The base interface for any chunk received from the AgentOS streaming API.
 */
export interface AgentOSResponseChunk {
  type: AgentOSResponseChunkType;
  streamId: string;
  gmiInstanceId: string;
  personaId: string;
  isFinal: boolean;
  timestamp: string;
  metadata?: Record<string, any>;
}

/**
 * @typedef {Object} AgentOSTextDeltaChunk
 * Represents a piece of textual response generated by the agent.
 * @augments {AgentOSResponseChunk}
 */
export interface AgentOSTextDeltaChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.TEXT_DELTA;
  textDelta: string;
}

/**
 * @typedef {Object} AgentOSSystemProgressChunk
 * Provides updates on the internal progress of the AgentOS.
 * @augments {AgentOSResponseChunk}
 */
export interface AgentOSSystemProgressChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.SYSTEM_PROGRESS;
  message: string;
  progressPercentage?: number;
  statusCode?: string;
}

/**
 * @typedef {Object} AgentOSToolCallRequestChunk
 * Informs the client that the agent has decided to call one or more tools.
 * @augments {AgentOSResponseChunk}
 */
export interface AgentOSToolCallRequestChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.TOOL_CALL_REQUEST;
  toolCalls: ToolCallRequest[]; // Using ToolCallRequest consistently
  rationale?: string;
}

/**
 * @typedef {Object} AgentOSToolResultEmissionChunk
 * Provides the client with the result of a tool call that was previously requested.
 * @augments {AgentOSResponseChunk}
 */
export interface AgentOSToolResultEmissionChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.TOOL_RESULT_EMISSION;
  toolCallId: string;
  toolName: string;
  toolResult: any;
  isSuccess: boolean;
  errorMessage?: string;
}


/**
 * @typedef {Object} AgentOSUICommandChunk
 * Contains instructions for the frontend to render or update dynamic UI components.
 * @augments {AgentOSResponseChunk}
 */
export interface AgentOSUICommandChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.UI_COMMAND;
  uiCommands: UICommand[];
}

/**
 * @typedef {Object} AgentOSFinalResponseChunk
 * The final, comprehensive output for a given turn.
 * @augments {AgentOSResponseChunk}
 */
export interface AgentOSFinalResponseChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.FINAL_RESPONSE;
  finalResponseText: string | null;
  /**
   * Plain-text rendering of `finalResponseText` intended for voice/TTS and logs.
   * When omitted, clients can derive it by stripping Markdown.
   */
  finalResponseTextPlain?: string | null;
  finalToolCalls?: ToolCallRequest[]; // Using ToolCallRequest consistently
  finalUiCommands?: UICommand[];
  audioOutput?: AudioOutputConfig;
  imageOutput?: ImageOutputConfig;
  usage?: CostAggregator;
  reasoningTrace?: ReasoningTrace[];
  error?: { code: string; message: string; details?: any };
  updatedConversationContext?: ConversationContext;
  activePersonaDetails?: Partial<IPersonaDefinition>;
}

/**
 * @typedef {Object} AgentOSErrorChunk
 * Signals that an error occurred, potentially leading to stream termination.
 * @augments {AgentOSResponseChunk}
 */
export interface AgentOSErrorChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.ERROR;
  code: string; // This should align with GMIErrorCode values
  message: string;
  details?: any;
}

/**
 * @typedef {Object} AgentOSMetadataUpdateChunk
 * Provides updates on metadata relevant to the session or GMI.
 * @augments {AgentOSResponseChunk}
 */
export interface AgentOSMetadataUpdateChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.METADATA_UPDATE;
  updates: Record<string, any>;
}

/**
 * @typedef {Object} AgentOSWorkflowUpdateChunk
 * Broadcasts workflow progress updates to streaming clients.
 * @augments {AgentOSResponseChunk}
 */
export interface AgentOSWorkflowUpdateChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.WORKFLOW_UPDATE;
  workflow: WorkflowProgressUpdate;
}

/**
 * @typedef {Object} AgentOSAgencyUpdateChunk
 * Communicates the state of the active Agency coordinating the workflow.
 * @augments {AgentOSResponseChunk}
 */
export interface AgentOSAgencyUpdateChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.AGENCY_UPDATE;
  agency: {
    agencyId: string;
    workflowId: string;
    conversationId?: string;
    seats: Array<{
      roleId: string;
      gmiInstanceId: string;
      personaId: string;
      metadata?: Record<string, unknown>;
    }>;
    metadata?: Record<string, unknown>;
  };
}

/**
 * @typedef {Object} AgentOSProvenanceEventChunk
 * Broadcasts provenance events (signed ledger entries) to streaming clients.
 * @augments {AgentOSResponseChunk}
 */
export interface AgentOSProvenanceEventChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.PROVENANCE_EVENT;
  eventType: string;
  eventId: string;
  sequence: number;
  hash: string;
  signature?: string;
  payload?: Record<string, unknown>;
}

/**
 * @typedef {AgentOSTextDeltaChunk | AgentOSSystemProgressChunk | AgentOSToolCallRequestChunk | AgentOSToolResultEmissionChunk | AgentOSUICommandChunk | AgentOSFinalResponseChunk | AgentOSErrorChunk | AgentOSMetadataUpdateChunk} AgentOSResponse
 * Union type representing any possible chunk that can be streamed from AgentOS.
 */
export type AgentOSResponse =
  | AgentOSTextDeltaChunk
  | AgentOSSystemProgressChunk
  | AgentOSToolCallRequestChunk
  | AgentOSToolResultEmissionChunk
  | AgentOSUICommandChunk
  | AgentOSFinalResponseChunk
  | AgentOSErrorChunk
  | AgentOSMetadataUpdateChunk
  | AgentOSWorkflowUpdateChunk
  | AgentOSAgencyUpdateChunk
  | AgentOSProvenanceEventChunk;
