/**
 * @file IMemoryAdapter.ts
 * @version 1.1.0
 * @description Interface for a memory adapter responsible for long-term storage
 * and retrieval of conversation history and related contextual data.
 * V1.0.1: Aligned IStoredConversationTurn.usage with ILlmUsage (tokens can be null).
 * V1.1.0: Added optional tool_calls and tool_call_id to IStoredConversationTurn.
 */

import type { ILlmToolCall, ILlmUsage } from '../llm/llm.interfaces';

/**
 * Represents the token usage for an LLM call, aligning with ILlmUsage.
 */
export interface IStoredLlmUsage extends ILlmUsage {}

/**
 * Represents a turn in the conversation suitable for storage.
 */
export interface IStoredConversationTurn {
  /** Unique ID for this specific turn in storage (e.g., UUID or DB auto-increment). */
  storageId: string; // Typically generated by the adapter on store
  /** The agent associated with this turn (e.g., 'tutor', 'codingAssistant'). */
  agentId: string;
  /** The conversation session ID this turn belongs to. */
  conversationId: string;
  /** Role of the message author ('user', 'assistant', 'system', 'tool'). */
  role: 'user' | 'assistant' | 'system' | 'tool';
  /**
   * Textual content of the message.
   * For an assistant message that results in tool_calls, this might be null or introductory text.
   * For a tool role message, this is the result of the tool execution.
   */
  content: string | null;
  /** Timestamp (milliseconds epoch) of the message. */
  timestamp: number;
  /** Model used for assistant's response, if applicable. */
  model?: string;
  /** Token usage for assistant's response, if applicable. */
  usage?: IStoredLlmUsage;
  /**
   * Optional: The tool calls generated by the assistant.
   * This is stored with the assistant message that initiated the calls.
   * Stored as a JSON string in the database.
   */
  tool_calls?: ILlmToolCall[]; // Stored as JSON string in DB, parsed on retrieval
  /**
   * Optional: The ID of the tool call this message is a result for.
   * This is present on 'tool' role messages.
   */
  tool_call_id?: string;
  /** Optional metadata associated with this turn (e.g., relevance score, key entities from that turn). Stored as JSON string. */
  metadata?: Record<string, any>; // Stored as JSON string in DB, parsed on retrieval
  /** Optional summary of this turn, if applicable for long-term storage. */
  summary?: string;
}

/**
 * Options for retrieving conversation history.
 */
export interface IMemoryRetrievalOptions {
  /** Maximum number of turns to retrieve. */
  limit?: number;
  /**
   * When `limit` is set, control which edge of the conversation to fetch.
   * - `true` (default): fetch the most recent turns.
   * - `false`: fetch the oldest turns matching the filters.
   */
  fetchMostRecent?: boolean;
  /** Retrieve turns before this timestamp (milliseconds epoch). */
  beforeTimestamp?: number;
  /** Retrieve turns after this timestamp (milliseconds epoch). */
  afterTimestamp?: number;
  /** Filter by specific agent ID. */
  agentId?: string;
  /**
   * If true, aims to retrieve summarized versions of older turns where available,
   * and detailed recent turns. Implementation is adapter-specific.
   */
  preferSummariesForOlder?: boolean;
}

/**
 * @interface IMemoryAdapter
 * @description Defines the contract for services that manage persistent
 * conversational memory.
 */
export interface IMemoryAdapter {
  /**
   * Initializes the memory adapter (e.g., connect to database, create tables).
   * @async
   * @returns {Promise<void>}
   */
  initialize(): Promise<void>;

  /**
   * Stores a single conversation turn.
   * @async
   * @param {string} userId - The ID of the user associated with the conversation.
   * @param {string} conversationId - The unique ID of the conversation session.
   * @param {Omit<IStoredConversationTurn, 'storageId' | 'conversationId'>} turnData - The conversation turn data to store.
   * The `content` can be `null` if `tool_calls` are present for an assistant message.
   * `tool_call_id` should be provided for `role: 'tool'` messages.
   * `tool_calls` and `metadata` will be stringified if provided.
   * @returns {Promise<string>} A promise that resolves to the storageId of the stored turn.
   * @throws {Error} If storing the turn fails.
   */
  storeConversationTurn(
    userId: string,
    conversationId: string,
    turnData: Omit<IStoredConversationTurn, 'storageId' | 'conversationId'>
  ): Promise<string>;

  /**
   * Retrieves conversation turns for a given user and conversation ID.
   * `tool_calls` and `metadata` will be parsed from JSON strings.
   * @async
   * @param {string} userId - The ID of the user.
   * @param {string} conversationId - The ID of the conversation.
   * @param {IMemoryRetrievalOptions} [options] - Optional filtering and retrieval options.
   * @returns {Promise<IStoredConversationTurn[]>} A promise that resolves to an array of stored turns.
   */
  retrieveConversationTurns(
    userId: string,
    conversationId: string,
    options?: IMemoryRetrievalOptions
  ): Promise<IStoredConversationTurn[]>;

  /**
   * Retrieves all conversation sessions for a user.
   * @async
   * @param {string} userId - The ID of the user.
   * @param {number} [limit=20] - Max number of recent sessions to retrieve.
   * @param {number} [offset=0] - Offset for pagination.
   * @returns {Promise<Array<{ conversationId: string; lastActivity: number; agentId?: string; summary?: string; turnCount?: number }>>}
   */
  listUserConversations(
    userId: string,
    limit?: number,
    offset?: number
  ): Promise<
    Array<{
      conversationId: string;
      lastActivity: number;
      agentId?: string;
      summary?: string;
      turnCount?: number;
      persona?: string | null;
    }>
  >;

  /**
   * Stores or clears a custom persona override for a conversation.
   * @param userId The ID of the user owning the conversation.
   * @param conversationId The unique ID of the conversation session.
   * @param agentId The agent associated with the conversation.
   * @param persona The persona text to persist, or null to clear it.
   * @param timestamp Optional timestamp used when creating the conversation record.
   */
  setConversationPersona(
    userId: string,
    conversationId: string,
    agentId: string,
    persona: string | null,
    timestamp?: number
  ): Promise<void>;

  /**
   * Retrieves the stored persona override for a conversation, if present.
   * @param userId The ID of the user owning the conversation.
   * @param conversationId The conversation whose persona should be loaded.
   * @returns The persona text or null when none is stored.
   */
  getConversationPersona(userId: string, conversationId: string): Promise<string | null>;

  /**
   * (Optional / Future) Generates or updates a summary for a given conversation or a segment of it.
   * @async
   * @param {string} userId - The ID of the user.
   * @param {string} conversationId - The ID of the conversation to summarize.
   * @param {string} [segmentId] - Optional ID of a specific segment within the conversation to summarize.
   * @returns {Promise<string>} A promise that resolves to the generated summary.
   */
  summarizeConversation?(
    userId: string,
    conversationId: string,
    segmentId?: string
  ): Promise<string>;

  /**
   * (Optional / Future) Deletes a conversation and all its turns.
   * @async
   * @param {string} userId - The ID of the user.
   * @param {string} conversationId - The ID of the conversation to delete.
   * @returns {Promise<void>}
   */
  deleteConversation?(userId: string, conversationId: string): Promise<void>;

  /**
   * (Optional / Future) Archives a conversation.
   * @async
   * @param {string} userId - The ID of the user.
   * @param {string} conversationId - The ID of the conversation to archive.
   * @returns {Promise<void>}
   */
  archiveConversation?(userId: string, conversationId: string): Promise<void>;

  /**
   * (Optional / Future) Searches through the user's conversation history.
   * @async
   * @param {string} userId - The ID of the user.
   * @param {string} searchQuery - The query string to search for.
   * @param {number} [limit=10] - Max number of results to return.
   * @returns {Promise<IStoredConversationTurn[]>} Relevant conversation turns.
   */
  searchHistory?(
    userId: string,
    searchQuery: string,
    limit?: number
  ): Promise<IStoredConversationTurn[]>;

  /**
   * Prunes old or less relevant conversation turns for a user to manage storage.
   * @async
   * @param {string} userId - The user ID whose history needs pruning.
   * @param {object} [criteria] - Optional criteria for pruning.
   * @returns {Promise<{ prunedTurnsCount: number; remainingTurnsCount: number }>}
   */
  pruneHistory(
    userId: string,
    criteria?: Record<string, any>
  ): Promise<{ prunedTurnsCount: number; remainingTurnsCount: number }>;

  /**
   * Closes the connection to the memory store.
   * @async
   * @returns {Promise<void>}
   */
  disconnect(): Promise<void>;
}
