"use client"

/**
 * Quarry Codex Stats Dashboard
 * 
 * Displays live analytics from the codex-report.json generated by GitHub Actions.
 * Shows:
 * - Total weaves/looms/strands
 * - Validation health
 * - Quality metrics
 * - Categorization breakdown
 * - Vocabulary insights
 * - Last update timestamp
 */

import React, { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { 
  BarChart3, TrendingUp, AlertCircle, CheckCircle2, Clock, 
  FileText, Folder, Layers, Tag, Sparkles, RefreshCw, ExternalLink 
} from 'lucide-react'

interface CodexReport {
  summary: {
    totalFiles: number
    indexedFiles: number
    skippedFiles: number
    validFiles: number
    filesWithErrors: number
    filesWithWarnings: number
    filesWithSuggestions: number
  }
  categorization: {
    bySubject: Record<string, number>
    byTopic: Record<string, number>
    byDifficulty: Record<string, number>
    confidenceScores: Array<{
      file: string
      category: string
      score: number
    }>
  }
  validation: {
    commonErrors: Record<string, number>
    commonWarnings: Record<string, number>
    fileErrors: Array<{ path: string; errors: string[] }>
    fileWarnings: Array<{ path: string; warnings: string[] }>
  }
  vocabulary: {
    totalUniqueTerms: number
    suggestedAdditions: Array<{ term: string; frequency: number }>
  }
}

export default function CodexStats({ compact = false }: { compact?: boolean }) {
  const [report, setReport] = useState<CodexReport | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null)
  const [refreshing, setRefreshing] = useState(false)

  const loadReport = async () => {
    setRefreshing(true)
    try {
      // Try GitHub Actions index branch first, then fall back to local
      const sources = [
        'https://raw.githubusercontent.com/framersai/quarry/index/codex-report.json',
        '/codex-report.json'
      ]

      let data: CodexReport | null = null

      for (const url of sources) {
        try {
          const response = await fetch(url, { cache: 'no-store' })
          if (response.ok) {
            data = await response.json()
            break
          }
        } catch {
          // try next source
        }
      }

      if (!data) {
        throw new Error('Could not load codex report from any source')
      }

      setReport(data)
      setLastUpdated(new Date())
      setError(null)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load report')
    } finally {
      setLoading(false)
      setRefreshing(false)
    }
  }

  useEffect(() => {
    loadReport()
    
    // Auto-refresh every 5 minutes
    const interval = setInterval(loadReport, 5 * 60 * 1000)
    return () => clearInterval(interval)
  }, [])

  if (loading) {
    return (
      <div className="flex items-center justify-center p-8">
        <RefreshCw className="w-6 h-6 animate-spin text-gray-400" />
      </div>
    )
  }

  if (error || !report) {
    return (
      <div className="p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-xl flex items-start gap-3">
        <AlertCircle className="w-5 h-5 text-red-600 dark:text-red-400 flex-shrink-0 mt-0.5" />
        <div className="flex-1">
          <p className="text-red-800 dark:text-red-200 text-sm">
            {error || 'Failed to load stats'}
          </p>
          <button
            onClick={loadReport}
            className="mt-2 text-sm text-red-600 dark:text-red-400 hover:underline"
          >
            Try again
          </button>
        </div>
      </div>
    )
  }

  const healthScore = Math.round(
    (report.summary.validFiles / report.summary.totalFiles) * 100
  )

  if (compact) {
    return (
      <div className="flex items-center gap-4 p-4 bg-gradient-to-r from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20 rounded-xl border border-purple-200 dark:border-purple-800">
        <div className="flex items-center gap-2">
          <Layers className="w-5 h-5 text-purple-600 dark:text-purple-400" />
          <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
            {report.summary.indexedFiles} strands
          </span>
        </div>
        
        <div className="flex items-center gap-2">
          <CheckCircle2 className="w-5 h-5 text-green-600 dark:text-green-400" />
          <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
            {healthScore}% healthy
          </span>
        </div>
        
        {lastUpdated && (
          <div className="flex items-center gap-2 ml-auto">
            <Clock className="w-4 h-4 text-gray-400" />
            <span className="text-xs text-gray-500 dark:text-gray-400">
              {lastUpdated.toLocaleTimeString()}
            </span>
          </div>
        )}
        
        <button
          onClick={loadReport}
          disabled={refreshing}
          className="p-1.5 hover:bg-white/50 dark:hover:bg-gray-800/50 rounded-lg transition-colors disabled:opacity-50"
        >
          <RefreshCw className={`w-4 h-4 text-gray-600 dark:text-gray-400 ${refreshing ? 'animate-spin' : ''}`} />
        </button>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <BarChart3 className="w-6 h-6 text-purple-600 dark:text-purple-400" />
            Codex Analytics
          </h3>
          {lastUpdated && (
            <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
              Last updated: {lastUpdated.toLocaleString()}
            </p>
          )}
        </div>
        
        <button
          onClick={loadReport}
          disabled={refreshing}
          className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg transition-colors disabled:opacity-50"
        >
          <RefreshCw className={`w-4 h-4 ${refreshing ? 'animate-spin' : ''}`} />
          <span className="text-sm font-medium">Refresh</span>
        </button>
      </div>

      {/* Overview Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard
          icon={<FileText className="w-5 h-5" />}
          label="Total Strands"
          value={report.summary.indexedFiles}
          color="purple"
        />
        
        <StatCard
          icon={<CheckCircle2 className="w-5 h-5" />}
          label="Valid Files"
          value={report.summary.validFiles}
          subValue={`${healthScore}%`}
          color="green"
        />
        
        <StatCard
          icon={<AlertCircle className="w-5 h-5" />}
          label="With Errors"
          value={report.summary.filesWithErrors}
          color="red"
        />
        
        <StatCard
          icon={<Sparkles className="w-5 h-5" />}
          label="Suggestions"
          value={report.summary.filesWithSuggestions}
          color="blue"
        />
      </div>

      {/* Categorization Breakdown */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* By Subject */}
        <div className="p-6 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700">
          <h4 className="text-lg font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
            <Tag className="w-5 h-5 text-purple-600 dark:text-purple-400" />
            By Subject
          </h4>
          <div className="space-y-3">
            {Object.entries(report.categorization.bySubject)
              .sort((a, b) => b[1] - a[1])
              .slice(0, 5)
              .map(([subject, count]) => (
                <div key={subject} className="flex items-center justify-between">
                  <span className="text-sm text-gray-700 dark:text-gray-300 capitalize">
                    {subject}
                  </span>
                  <div className="flex items-center gap-2">
                    <div className="w-32 h-2 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                      <div
                        className="h-full bg-gradient-to-r from-purple-500 to-pink-500 rounded-full"
                        style={{
                          width: `${(count / report.summary.indexedFiles) * 100}%`
                        }}
                      />
                    </div>
                    <span className="text-sm font-medium text-gray-900 dark:text-white w-8 text-right">
                      {count}
                    </span>
                  </div>
                </div>
              ))}
          </div>
        </div>

        {/* By Difficulty */}
        <div className="p-6 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700">
          <h4 className="text-lg font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-blue-600 dark:text-blue-400" />
            By Difficulty
          </h4>
          <div className="space-y-3">
            {Object.entries(report.categorization.byDifficulty)
              .sort((a, b) => {
                const order = { beginner: 0, intermediate: 1, advanced: 2, expert: 3 }
                return order[a[0] as keyof typeof order] - order[b[0] as keyof typeof order]
              })
              .map(([difficulty, count]) => (
                <div key={difficulty} className="flex items-center justify-between">
                  <span className="text-sm text-gray-700 dark:text-gray-300 capitalize">
                    {difficulty}
                  </span>
                  <div className="flex items-center gap-2">
                    <div className="w-32 h-2 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                      <div
                        className={`h-full rounded-full ${
                          difficulty === 'beginner' ? 'bg-green-500' :
                          difficulty === 'intermediate' ? 'bg-blue-500' :
                          difficulty === 'advanced' ? 'bg-orange-500' :
                          'bg-red-500'
                        }`}
                        style={{
                          width: `${(count / report.summary.indexedFiles) * 100}%`
                        }}
                      />
                    </div>
                    <span className="text-sm font-medium text-gray-900 dark:text-white w-8 text-right">
                      {count}
                    </span>
                  </div>
                </div>
              ))}
          </div>
        </div>
      </div>

      {/* Vocabulary Insights */}
      {report.vocabulary.suggestedAdditions.length > 0 && (
        <div className="p-6 bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20 rounded-xl border border-purple-200 dark:border-purple-800">
          <h4 className="text-lg font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-purple-600 dark:text-purple-400" />
            Suggested Vocabulary Additions
          </h4>
          <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
            These terms appear frequently but aren't in the controlled vocabulary yet:
          </p>
          <div className="flex flex-wrap gap-2">
            {report.vocabulary.suggestedAdditions.slice(0, 10).map(({ term, frequency }) => (
              <span
                key={term}
                className="px-3 py-1.5 bg-white dark:bg-gray-800 border border-purple-200 dark:border-purple-700 rounded-lg text-sm"
              >
                <span className="font-medium text-gray-900 dark:text-white">{term}</span>
                <span className="ml-2 text-gray-500 dark:text-gray-400">×{frequency}</span>
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Validation Issues */}
      {(report.summary.filesWithErrors > 0 || report.summary.filesWithWarnings > 0) && (
        <div className="p-6 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700">
          <h4 className="text-lg font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
            <AlertCircle className="w-5 h-5 text-red-600 dark:text-red-400" />
            Validation Issues
          </h4>
          
          {Object.keys(report.validation.commonErrors).length > 0 && (
            <div className="mb-4">
              <h5 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Most Common Errors
              </h5>
              <div className="space-y-2">
                {Object.entries(report.validation.commonErrors)
                  .sort((a, b) => b[1] - a[1])
                  .slice(0, 5)
                  .map(([error, count]) => (
                    <div key={error} className="flex items-center justify-between text-sm">
                      <span className="text-gray-600 dark:text-gray-400">{error}</span>
                      <span className="font-medium text-red-600 dark:text-red-400">{count} files</span>
                    </div>
                  ))}
              </div>
            </div>
          )}
          
          <a
            href="https://github.com/framersai/quarry/actions"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 text-sm text-purple-600 dark:text-purple-400 hover:underline"
          >
            View full report on GitHub
            <ExternalLink className="w-4 h-4" />
          </a>
        </div>
      )}
    </div>
  )
}

function StatCard({ 
  icon, 
  label, 
  value, 
  subValue, 
  color 
}: { 
  icon: React.ReactNode
  label: string
  value: number
  subValue?: string
  color: 'purple' | 'green' | 'red' | 'blue'
}) {
  const colorClasses = {
    purple: 'from-purple-500 to-pink-500',
    green: 'from-green-500 to-emerald-500',
    red: 'from-red-500 to-orange-500',
    blue: 'from-blue-500 to-cyan-500'
  }

  return (
    <div className="p-6 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700">
      <div className={`inline-flex p-2 bg-gradient-to-br ${colorClasses[color]} rounded-lg text-white mb-3`}>
        {icon}
      </div>
      <div className="text-3xl font-bold text-gray-900 dark:text-white mb-1">
        {value.toLocaleString()}
        {subValue && (
          <span className="text-lg font-normal text-gray-500 dark:text-gray-400 ml-2">
            {subValue}
          </span>
        )}
      </div>
      <div className="text-sm text-gray-600 dark:text-gray-400">
        {label}
      </div>
    </div>
  )
}

