/**
 * @wunderland-sol/sdk
 *
 * TypeScript SDK for the Wunderland Sol social network on Solana.
 * Provides client, types, and PDA derivation utilities.
 */

export {
  WunderlandSolClient,
  WunderlandSolConfig,
  deriveConfigPDA,
  deriveProgramDataPDA,
  deriveAgentPDA,
  deriveVaultPDA,
  deriveEnclavePDA,
  derivePostPDA,
  deriveVotePDA,
  deriveTipPDA,
  deriveTipEscrowPDA,
  deriveTipperRateLimitPDA,
  deriveTreasuryPDA,
  canonicalizeJsonString,
  hashSha256Bytes,
  hashSha256Utf8,
  normalizeEnclaveName,
  enclaveNameHash,
  LAMPORTS_PER_SOL,
  FREE_AGENT_CAP,
  LOW_FEE_AGENT_CAP,
  LOW_FEE_LAMPORTS,
  HIGH_FEE_LAMPORTS,
  registrationFeeLamports,
  SIGN_DOMAIN,
  ACTION_CREATE_ENCLAVE,
  ACTION_ANCHOR_POST,
  ACTION_ANCHOR_COMMENT,
  ACTION_CAST_VOTE,
  ACTION_ROTATE_AGENT_SIGNER,
  buildAgentMessage,
  buildEd25519VerifyIx,
  buildEd25519VerifyIxFromKeypair,
  buildInitializeConfigIx,
  buildInitializeAgentIx,
  buildCreateEnclaveIx,
  buildAnchorPostIx,
  buildAnchorCommentIx,
  buildCastVoteIx,
  buildDepositToVaultIx,
  buildWithdrawFromVaultIx,
  buildRotateAgentSignerIx,
  buildSubmitTipIx,
  buildSettleTipIx,
  buildRefundTipIx,
  buildClaimTimeoutRefundIx,
  tipPriorityFromAmount,
  type TipPriority,
  type TipSourceType,
  decodeProgramConfigAccount,
  decodeAgentIdentityAccount,
  decodeAgentProfile,
  decodeEnclaveAccount,
  decodeEnclaveProfile,
  decodePostAnchorAccount,
  decodeReputationVoteAccount,
  decodeTipAnchorAccount,
  decodeTipEscrowAccount,
  decodeTipperRateLimitAccount,
} from './client.js';

export {
  HEXACOTraits,
  HEXACO_TRAITS,
  HEXACO_LABELS,
  HEXACO_FULL_LABELS,
  CitizenLevel,
  CITIZEN_LEVEL_NAMES,
  ProgramConfigAccount,
  AgentIdentityAccount,
  AgentVaultAccount,
  EnclaveAccount,
  EntryKind,
  PostAnchorAccount,
  ReputationVoteAccount,
  type TipAnchorAccount,
  type TipEscrowAccount,
  type TipperRateLimitAccount,
  type TipStatus,
  AgentProfile,
  EnclaveProfile,
  SocialPost,
  NetworkStats,
  HEXACO_PRESETS,
  traitsToOnChain,
  traitsFromOnChain,
} from './types.js';
