#!/bin/bash

###############################################################################
# Frame Codex Full Re-Catalog Script
#
# This script triggers a complete re-indexing and re-categorization of ALL
# content in the Frame Codex repository. It will:
# 
# 1. Run static NLP analysis (TF-IDF, n-grams) on all markdown files
# 2. Auto-generate/update metadata where missing
# 3. Suggest better categorization based on content analysis
# 4. Create a PR with all proposed changes (requires approval by default)
# 5. Optionally auto-merge if AUTO_CATALOG_MERGE=true secret is set
#
# Usage:
#   ./scripts/retrigger-full-catalog.sh
#   ./scripts/retrigger-full-catalog.sh --dry-run
#   ./scripts/retrigger-full-catalog.sh --auto-merge
#
# Environment Variables:
#   AUTO_CATALOG_MERGE=true    # Enable auto-merge (default: false)
#   GH_PAT=ghp_...            # GitHub token for PR creation
###############################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse arguments
DRY_RUN=false
FORCE_AUTO_MERGE=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --auto-merge)
      FORCE_AUTO_MERGE=true
      shift
      ;;
    *)
      echo -e "${RED}Unknown option: $1${NC}"
      exit 1
      ;;
  esac
done

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  Frame Codex Full Re-Catalog & Metadata Update            ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if we're in the right directory
if [ ! -f "package.json" ] || [ ! -d "weaves" ]; then
  echo -e "${RED}❌ Error: Must run from apps/codex directory${NC}"
  exit 1
fi

# Check dependencies
if ! command -v node &> /dev/null; then
  echo -e "${RED}❌ Error: Node.js not found${NC}"
  exit 1
fi

if ! command -v git &> /dev/null; then
  echo -e "${RED}❌ Error: Git not found${NC}"
  exit 1
fi

echo -e "${GREEN}✓${NC} Environment checks passed"
echo ""

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
  echo -e "${YELLOW}📦 Installing dependencies...${NC}"
  npm install
fi

# Run full catalog with validation
echo -e "${BLUE}🔍 Running full catalog analysis...${NC}"
echo -e "${YELLOW}   This will analyze ALL markdown files with static NLP${NC}"
echo ""

if [ "$DRY_RUN" = true ]; then
  echo -e "${YELLOW}[DRY RUN MODE - No changes will be made]${NC}"
  npm run index -- --validate
  echo ""
  echo -e "${GREEN}✓${NC} Dry run complete. Check codex-report.json for analysis."
  exit 0
fi

# Create a new branch for changes
BRANCH_NAME="catalog/full-reindex-$(date +%s)"
echo -e "${BLUE}🌿 Creating branch: ${BRANCH_NAME}${NC}"
git checkout -b "$BRANCH_NAME"

# Run indexer
npm run index -- --validate

# Check if there are changes to commit
if git diff --quiet && git diff --cached --quiet; then
  echo -e "${YELLOW}ℹ️  No changes detected. Index is up to date.${NC}"
  git checkout main
  git branch -D "$BRANCH_NAME"
  exit 0
fi

# Show what changed
echo ""
echo -e "${BLUE}📊 Changes detected:${NC}"
git status --short

# Commit changes
echo ""
echo -e "${BLUE}💾 Committing changes...${NC}"
git add codex-index.json codex-report.json

# Generate commit message from report
TOTAL_FILES=$(node -e "const r = require('./codex-report.json'); console.log(r.summary.indexedFiles)")
VALID_FILES=$(node -e "const r = require('./codex-report.json'); console.log(r.summary.validFiles)")
ERROR_FILES=$(node -e "const r = require('./codex-report.json'); console.log(r.summary.filesWithErrors)")

git commit -m "chore: full catalog re-index and metadata update

Automated re-catalog of all Frame Codex content:
- Total files indexed: ${TOTAL_FILES}
- Valid files: ${VALID_FILES}
- Files with errors: ${ERROR_FILES}

Generated by: scripts/retrigger-full-catalog.sh
Timestamp: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"

# Push branch
echo ""
echo -e "${BLUE}⬆️  Pushing branch...${NC}"
git push origin "$BRANCH_NAME"

# Create PR
echo ""
echo -e "${BLUE}📝 Creating Pull Request...${NC}"

# Check if GH_PAT is set
if [ -z "$GH_PAT" ]; then
  echo -e "${YELLOW}⚠️  GH_PAT not set. Please create PR manually:${NC}"
  echo ""
  echo "  git push origin $BRANCH_NAME"
  echo "  gh pr create --title 'Full Catalog Re-Index' --body 'Automated metadata update'"
  echo ""
  exit 0
fi

# Determine if auto-merge should be enabled
AUTO_MERGE="${AUTO_CATALOG_MERGE:-false}"
if [ "$FORCE_AUTO_MERGE" = true ]; then
  AUTO_MERGE=true
fi

# Create PR body
PR_BODY="## Automated Full Catalog Re-Index

This PR updates the search index and metadata for all Frame Codex content.

### Summary
- **Total files indexed**: ${TOTAL_FILES}
- **Valid files**: ${VALID_FILES}
- **Files with errors**: ${ERROR_FILES}

### Changes
- Updated \`codex-index.json\` with latest TF-IDF analysis
- Updated \`codex-report.json\` with validation results
- All changes are automatically generated via static NLP

### Auto-Merge
- **Enabled**: ${AUTO_MERGE}
- **Triggered by**: \`scripts/retrigger-full-catalog.sh\`

---

Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
"

# Create PR using GitHub API
PR_RESPONSE=$(curl -s -X POST \
  -H "Authorization: Bearer $GH_PAT" \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/framersai/codex/pulls \
  -d "{
    \"title\": \"chore: full catalog re-index ($(date +%Y-%m-%d))\",
    \"head\": \"$BRANCH_NAME\",
    \"base\": \"main\",
    \"body\": $(echo "$PR_BODY" | jq -Rs .)
  }")

PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')
PR_URL=$(echo "$PR_RESPONSE" | jq -r '.html_url')

if [ "$PR_NUMBER" = "null" ]; then
  echo -e "${RED}❌ Failed to create PR${NC}"
  echo "$PR_RESPONSE" | jq .
  exit 1
fi

echo -e "${GREEN}✓${NC} Pull Request created: ${PR_URL}"

# Auto-merge if enabled
if [ "$AUTO_MERGE" = "true" ]; then
  echo ""
  echo -e "${YELLOW}🤖 Auto-merge enabled. Merging PR...${NC}"
  
  # Wait a moment for CI to start
  sleep 5
  
  # Merge PR
  MERGE_RESPONSE=$(curl -s -X PUT \
    -H "Authorization: Bearer $GH_PAT" \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    https://api.github.com/repos/framersai/codex/pulls/${PR_NUMBER}/merge \
    -d '{
      "commit_title": "chore: full catalog re-index",
      "commit_message": "Automated merge of catalog update",
      "merge_method": "squash"
    }')
  
  if echo "$MERGE_RESPONSE" | jq -e '.merged' > /dev/null; then
    echo -e "${GREEN}✓${NC} PR merged successfully!"
  else
    echo -e "${YELLOW}⚠️  Auto-merge failed. Manual approval required.${NC}"
    echo -e "   Reason: $(echo "$MERGE_RESPONSE" | jq -r '.message')"
  fi
else
  echo ""
  echo -e "${YELLOW}ℹ️  Auto-merge disabled. PR requires manual approval.${NC}"
  echo -e "   To enable auto-merge, set: ${BLUE}AUTO_CATALOG_MERGE=true${NC}"
fi

# Return to main branch
git checkout main

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  ✓ Full catalog re-index complete!                        ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "📊 View report: ${BLUE}codex-report.json${NC}"
echo -e "🔗 Pull Request: ${BLUE}${PR_URL}${NC}"
echo ""

