/**
 * Creative Nonfiction Writing Prompts
 * @module lib/prompts/nonfictionPrompts
 *
 * 92 curated creative nonfiction prompts from various sources including
 * Ratika Deshpande, Elizabeth Lyons, Reedsy, Bookfox, DIY MFA, Final Draft,
 * and The Good Trade.
 *
 * Organized by category with mood associations for personalized filtering.
 */

import type { WritingPrompt, PromptCategory, PromptMode } from '@/lib/codex/prompts'
import type { MoodState } from '@/lib/codex/mood'

/**
 * Creative nonfiction prompts - 80 total
 */
export const NONFICTION_PROMPTS: WritingPrompt[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // REFLECTION (15 prompts)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'nr1',
    text: "Imagine you've traveled through time and encountered a younger version of yourself. What lesson would you share?",
    category: 'reflection',
    mood: ['reflective'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'reflect',
    tags: ['time', 'wisdom', 'self'],
  },
  {
    id: 'nr2',
    text: 'Tell me about a moment when you were terrified to do something, but you did it anyway.',
    category: 'reflection',
    mood: ['reflective', 'energetic'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'reflect',
    tags: ['courage', 'fear', 'growth'],
  },
  {
    id: 'nr3',
    text: 'What moment from your childhood set you on your current career path?',
    category: 'reflection',
    mood: ['reflective', 'curious'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'reflect',
    tags: ['childhood', 'career', 'destiny'],
  },
  {
    id: 'nr4',
    text: 'What adult had the most influence on molding who you are today?',
    category: 'reflection',
    mood: ['reflective', 'grateful'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'reflect',
    tags: ['mentor', 'influence', 'gratitude'],
  },
  {
    id: 'nr5',
    text: 'Write about a relationship that was unexpected or outside your usual type.',
    category: 'reflection',
    mood: ['reflective'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'reflect',
    tags: ['relationships', 'surprise', 'growth'],
  },
  {
    id: 'nr6',
    text: 'Write about something you do now that the old you would never believe.',
    category: 'reflection',
    mood: ['reflective', 'excited'],
    difficulty: 'beginner',
    estimatedTime: '10 min',
    mode: 'reflect',
    tags: ['change', 'growth', 'surprise'],
  },
  {
    id: 'nr7',
    text: 'What single event has most strongly shaped who you currently are?',
    category: 'reflection',
    mood: ['reflective'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'reflect',
    tags: ['pivotal', 'identity', 'transformation'],
  },
  {
    id: 'nr8',
    text: 'Revisit a moment you feel you will never be able to forget. Why is it unforgettable?',
    category: 'reflection',
    mood: ['reflective'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'reflect',
    tags: ['memory', 'significance', 'emotion'],
  },
  {
    id: 'nr9',
    text: 'Write about an experience that has made you more resilient.',
    category: 'reflection',
    mood: ['reflective', 'energetic'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'reflect',
    tags: ['resilience', 'strength', 'adversity'],
  },
  {
    id: 'nr10',
    text: 'What relationship in your life has caused the most pain? Write about the key scene.',
    category: 'reflection',
    mood: ['reflective', 'anxious'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'reflect',
    tags: ['pain', 'relationships', 'healing'],
  },
  {
    id: 'nr11',
    text: "Write about a time you chose to remain silent. Why didn't you speak?",
    category: 'reflection',
    mood: ['reflective'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'reflect',
    tags: ['silence', 'choice', 'restraint'],
  },
  {
    id: 'nr12',
    text: 'Describe a scene from your memory reimagined from an alternate perspective.',
    category: 'reflection',
    mood: ['reflective', 'creative'],
    difficulty: 'advanced',
    estimatedTime: '20 min',
    mode: 'both',
    tags: ['perspective', 'memory', 'creative'],
  },
  {
    id: 'nr13',
    text: 'Write about a fork in the road in your life, and how you made that decision.',
    category: 'reflection',
    mood: ['reflective'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'reflect',
    tags: ['decisions', 'paths', 'choice'],
  },
  {
    id: 'nr14',
    text: 'What do you want more than anything in life? Write about the burning core of your desire.',
    category: 'reflection',
    mood: ['reflective', 'energetic'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'reflect',
    tags: ['desire', 'dreams', 'passion'],
  },
  {
    id: 'nr15',
    text: 'Write about a time you felt like an outsider at an event.',
    category: 'reflection',
    mood: ['reflective', 'anxious'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'reflect',
    tags: ['belonging', 'outsider', 'social'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CREATIVE (15 prompts)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'nc1',
    text: "Write your autobiography using only other people's book titles.",
    category: 'creative',
    mood: ['creative'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'write',
    tags: ['autobiography', 'books', 'creative'],
  },
  {
    id: 'nc2',
    text: 'Take a boring moment from today and make it dramatic with ecstatic prose.',
    category: 'creative',
    mood: ['creative', 'energetic'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'write',
    tags: ['mundane', 'dramatic', 'prose'],
  },
  {
    id: 'nc3',
    text: 'Describe your favorite meal. Then describe a conflict with the people you shared it with.',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['food', 'conflict', 'memory'],
  },
  {
    id: 'nc4',
    text: 'Write about a date that took an unexpected turn.',
    category: 'creative',
    mood: ['creative', 'curious'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'write',
    tags: ['dating', 'surprise', 'story'],
  },
  {
    id: 'nc5',
    text: 'Rewrite a favorite childhood story with an alternative ending.',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['fairytale', 'rewrite', 'imagination'],
  },
  {
    id: 'nc6',
    text: 'Imagine a world where days are getting progressively shorter. How do your characters save humanity?',
    category: 'creative',
    mood: ['creative', 'energetic'],
    difficulty: 'advanced',
    estimatedTime: '30 min',
    mode: 'write',
    tags: ['scifi', 'adventure', 'stakes'],
  },
  {
    id: 'nc7',
    text: 'Write a scene where your main character wakes up on a train destined somewhere tropical.',
    category: 'creative',
    mood: ['creative', 'relaxed'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'write',
    tags: ['travel', 'mystery', 'opening'],
  },
  {
    id: 'nc8',
    text: 'You wake up with a silly superpower that makes you famous. What is it, and what goes wrong?',
    category: 'creative',
    mood: ['creative', 'excited'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['superpower', 'fantasy', 'discovery'],
  },
  {
    id: 'nc9',
    text: 'Write a story based on your most recent text message.',
    category: 'creative',
    mood: ['creative', 'curious'],
    difficulty: 'beginner',
    estimatedTime: '15 min',
    mode: 'write',
    tags: ['modern', 'communication', 'inspiration'],
  },
  {
    id: 'nc10',
    text: 'Create a mini-mythology to explain your morning coffee ritual.',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'write',
    tags: ['mythology', 'ritual', 'playful'],
  },
  {
    id: 'nc11',
    text: 'Write from the perspective of an inanimate object in your home.',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'write',
    tags: ['perspective', 'objects', 'imagination'],
  },
  {
    id: 'nc12',
    text: 'Describe your house disappearing and being replaced with a supermarket. What happens?',
    category: 'creative',
    mood: ['creative', 'curious'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['surreal', 'mystery', 'home'],
  },
  {
    id: 'nc13',
    text: "Write a comedic story from the perspective of a restaurant server on Valentine's Day.",
    category: 'creative',
    mood: ['creative', 'energetic'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['comedy', 'holiday', 'work'],
  },
  {
    id: 'nc14',
    text: 'Two friends discover their lake has magic powers. Write about their adventure.',
    category: 'creative',
    mood: ['creative', 'excited'],
    difficulty: 'intermediate',
    estimatedTime: '25 min',
    mode: 'write',
    tags: ['magic', 'friendship', 'adventure'],
  },
  {
    id: 'nc15',
    text: "Write a poem from the sun's perspective.",
    category: 'creative',
    mood: ['creative', 'peaceful'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'write',
    tags: ['poetry', 'nature', 'perspective'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PERSONAL (10 prompts)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'np2',
    text: 'What did you collect as a child or teenager? Why?',
    category: 'personal',
    mood: ['curious', 'relaxed'],
    difficulty: 'beginner',
    estimatedTime: '10 min',
    mode: 'reflect',
    tags: ['childhood', 'collections', 'hobby'],
  },
  {
    id: 'np4',
    text: 'Describe a family heirloom and why it matters to you.',
    category: 'personal',
    mood: ['reflective', 'grateful'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'reflect',
    tags: ['heirloom', 'family', 'meaning'],
  },
  {
    id: 'np5',
    text: "Write about the day you got your driver's license.",
    category: 'personal',
    mood: ['energetic', 'excited'],
    difficulty: 'beginner',
    estimatedTime: '10 min',
    mode: 'reflect',
    tags: ['milestone', 'freedom', 'coming-of-age'],
  },
  {
    id: 'np6',
    text: 'What nickname did you have growing up? Who gave it to you?',
    category: 'personal',
    mood: ['relaxed'],
    difficulty: 'beginner',
    estimatedTime: '10 min',
    mode: 'reflect',
    tags: ['nickname', 'identity', 'relationships'],
  },
  {
    id: 'np7',
    text: 'Write about your first pet, or the first thing you cared for.',
    category: 'personal',
    mood: ['reflective', 'grateful'],
    difficulty: 'beginner',
    estimatedTime: '15 min',
    mode: 'reflect',
    tags: ['pets', 'care', 'love'],
  },
  {
    id: 'np8',
    text: 'Tell the story of one of your family holiday gatherings.',
    category: 'personal',
    mood: ['relaxed', 'grateful'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'reflect',
    tags: ['family', 'holiday', 'tradition'],
  },
  {
    id: 'np10',
    text: 'How did your relationship with your city evolve as you grew up?',
    category: 'personal',
    mood: ['reflective', 'curious'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'reflect',
    tags: ['city', 'growth', 'place'],
  },
  {
    id: 'np13',
    text: 'Write a letter to someone who shaped who you are today.',
    category: 'personal',
    mood: ['reflective', 'grateful'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'reflect',
    tags: ['letter', 'gratitude', 'influence'],
  },
  {
    id: 'np14',
    text: "Tell a story you'd never want your parents to read.",
    category: 'personal',
    mood: ['creative', 'anxious'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'reflect',
    tags: ['secret', 'confession', 'truth'],
  },
  {
    id: 'np15',
    text: 'What was the best/worst letter you ever received or wrote?',
    category: 'personal',
    mood: ['reflective'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'reflect',
    tags: ['letter', 'communication', 'emotion'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PHILOSOPHICAL (10 prompts)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'nph1',
    text: 'What does it mean to say "I love you"? When did you first feel loved?',
    category: 'philosophical',
    mood: ['reflective', 'grateful'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'both',
    tags: ['love', 'meaning', 'emotion'],
  },
  {
    id: 'nph2',
    text: 'In the circle of life, beginnings are preceded by endings. Write about an ending that led to a beginning.',
    category: 'philosophical',
    mood: ['reflective'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'both',
    tags: ['cycles', 'endings', 'beginnings'],
  },
  {
    id: 'nph3',
    text: 'What makes you feel guilty? Explore a moment you are ashamed of.',
    category: 'philosophical',
    mood: ['reflective', 'anxious'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'reflect',
    tags: ['guilt', 'shame', 'morality'],
  },
  {
    id: 'nph4',
    text: 'How has your identity changed over your life? Compare scenes from your teens and now.',
    category: 'philosophical',
    mood: ['reflective', 'curious'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'both',
    tags: ['identity', 'change', 'growth'],
  },
  {
    id: 'nph5',
    text: "What is something you see others doing that you'd do differently if they knew what you know?",
    category: 'philosophical',
    mood: ['reflective'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'both',
    tags: ['wisdom', 'perspective', 'knowledge'],
  },
  {
    id: 'nph6',
    text: 'Write about a time you acted selflessly. What motivated you?',
    category: 'philosophical',
    mood: ['reflective', 'grateful'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'both',
    tags: ['selfless', 'motivation', 'kindness'],
  },
  {
    id: 'nph7',
    text: 'Creativity can process heartache. Write about the last time you felt grief.',
    category: 'philosophical',
    mood: ['reflective', 'peaceful'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'reflect',
    tags: ['grief', 'healing', 'creativity'],
  },
  {
    id: 'nph8',
    text: 'Consider the meaning of beauty and how it has evolved. Write about this.',
    category: 'philosophical',
    mood: ['reflective', 'curious'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'both',
    tags: ['beauty', 'meaning', 'evolution'],
  },
  {
    id: 'nph9',
    text: 'If you could give $100,000 to any charity, which would you choose and why?',
    category: 'philosophical',
    mood: ['reflective'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'both',
    tags: ['values', 'giving', 'priorities'],
  },
  {
    id: 'nph10',
    text: 'Scientists wonder about nature vs nurture. Where are you and your siblings today?',
    category: 'philosophical',
    mood: ['reflective', 'curious'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'both',
    tags: ['nature', 'nurture', 'family'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // EXPLORATION (8 prompts)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'ne1',
    text: 'Go through your search history and write about a topic you researched obsessively.',
    category: 'exploration',
    mood: ['curious', 'energetic'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['research', 'obsession', 'curiosity'],
  },
  {
    id: 'ne2',
    text: "Write a portrait of what's in your bookshelf at this moment.",
    category: 'exploration',
    mood: ['curious', 'relaxed'],
    difficulty: 'beginner',
    estimatedTime: '15 min',
    mode: 'write',
    tags: ['books', 'portrait', 'collection'],
  },
  {
    id: 'ne3',
    text: 'Research and write about the origin story of something you use daily.',
    category: 'exploration',
    mood: ['curious'],
    difficulty: 'intermediate',
    estimatedTime: '25 min',
    mode: 'write',
    tags: ['origins', 'research', 'everyday'],
  },
  {
    id: 'ne4',
    text: 'Describe your favorite room in your house and why it matters.',
    category: 'exploration',
    mood: ['relaxed', 'peaceful'],
    difficulty: 'beginner',
    estimatedTime: '15 min',
    mode: 'write',
    tags: ['home', 'space', 'comfort'],
  },
  {
    id: 'ne5',
    text: 'Write about a trip you took and where your fellow travelers ended up in life.',
    category: 'exploration',
    mood: ['curious', 'reflective'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['travel', 'connections', 'paths'],
  },
  {
    id: 'ne7',
    text: 'Write about a location close to your heart—your connection, however small.',
    category: 'exploration',
    mood: ['reflective', 'peaceful'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'write',
    tags: ['place', 'connection', 'meaning'],
  },
  {
    id: 'ne8',
    text: 'Write about an encounter with someone new who changed your life forever.',
    category: 'exploration',
    mood: ['curious', 'excited'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['encounter', 'change', 'people'],
  },
  {
    id: 'ne9',
    text: 'Describe your last vacation in present tense, as if living it now.',
    category: 'exploration',
    mood: ['relaxed', 'energetic'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'write',
    tags: ['vacation', 'present-tense', 'immersion'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PRACTICAL (7 prompts)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'npr1',
    text: "Document a skill you've mastered in a way others could follow.",
    category: 'practical',
    mood: ['focused'],
    difficulty: 'intermediate',
    estimatedTime: '25 min',
    mode: 'write',
    tags: ['skill', 'teaching', 'mastery'],
  },
  {
    id: 'npr2',
    text: "Create a troubleshooting guide for a problem you've solved before.",
    category: 'practical',
    mood: ['focused'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['troubleshooting', 'guide', 'problem-solving'],
  },
  {
    id: 'npr3',
    text: 'Write a guide to the best local spots only you know about.',
    category: 'practical',
    mood: ['energetic', 'relaxed'],
    difficulty: 'beginner',
    estimatedTime: '15 min',
    mode: 'write',
    tags: ['local', 'guide', 'secrets'],
  },
  {
    id: 'npr4',
    text: 'The one room in your house that drives you crazy—describe it and what it reveals about you.',
    category: 'practical',
    mood: ['focused', 'energetic'],
    difficulty: 'beginner',
    estimatedTime: '10 min',
    mode: 'reflect',
    tags: ['home', 'improvement', 'projects'],
  },
  {
    id: 'npr6',
    text: "Write about a resolution you didn't keep. What did releasing it teach you?",
    category: 'practical',
    mood: ['reflective'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'reflect',
    tags: ['resolutions', 'letting-go', 'lessons'],
  },
  {
    id: 'npr7',
    text: 'Document your ideal workflow for a creative task you do often.',
    category: 'practical',
    mood: ['focused'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['workflow', 'productivity', 'process'],
  },
  {
    id: 'npr8',
    text: 'Write a packing list and rationale for your dream trip.',
    category: 'practical',
    mood: ['relaxed', 'excited'],
    difficulty: 'beginner',
    estimatedTime: '15 min',
    mode: 'reflect',
    tags: ['travel', 'packing', 'planning'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LEARNING (7 prompts)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'nl1',
    text: 'Recall a key lesson that family tried to impart. How do you interpret it now?',
    category: 'learning',
    mood: ['reflective', 'curious'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'both',
    tags: ['family', 'lessons', 'wisdom'],
  },
  {
    id: 'nl2',
    text: "Write about something you're scared of and how you plan to overcome it.",
    category: 'learning',
    mood: ['reflective', 'energetic'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'both',
    tags: ['fear', 'courage', 'growth'],
  },
  {
    id: 'nl3',
    text: 'Explore an addiction you had or have. Describe the first time you tried it.',
    category: 'learning',
    mood: ['reflective'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'reflect',
    tags: ['addiction', 'honesty', 'self-awareness'],
  },
  {
    id: 'nl4',
    text: 'What challenge did you overcome? Write about the experience and lessons.',
    category: 'learning',
    mood: ['reflective', 'energetic'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'both',
    tags: ['challenge', 'overcome', 'lessons'],
  },
  {
    id: 'nl5',
    text: 'Recall someone you hated. Describe their behavior and try to understand why.',
    category: 'learning',
    mood: ['reflective'],
    difficulty: 'advanced',
    estimatedTime: '20 min',
    mode: 'reflect',
    tags: ['hate', 'understanding', 'empathy'],
  },
  {
    id: 'nl6',
    text: 'Write about a moment you learned to take your own advice.',
    category: 'learning',
    mood: ['reflective'],
    difficulty: 'intermediate',
    estimatedTime: '15 min',
    mode: 'both',
    tags: ['self-advice', 'wisdom', 'growth'],
  },
  {
    id: 'nl7',
    text: 'Pick an impactful childhood moment. Write about it from the lens of adulthood.',
    category: 'learning',
    mood: ['reflective', 'curious'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'both',
    tags: ['childhood', 'perspective', 'growth'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TECHNICAL/CRAFT (12 prompts) - Writing technique and skill-building
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'nt1',
    text: 'Two people who love each other are having the worst argument of their relationship. But here\'s the constraint: no one raises their voice. No shouting, no slamming doors. The tension must come entirely from what\'s said, what\'s left unsaid, and the silences between. Write this argument in a way that makes the reader hold their breath.',
    category: 'technical',
    mood: ['focused', 'creative'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'write',
    tags: ['dialogue', 'craft', 'tension'],
  },
  {
    id: 'nt2',
    text: 'Your character has never told a convincing lie in their life—they\'re known for their honesty, it\'s part of who they are. But now they\'re in a situation where the truth would destroy someone they love. Write the scene where they lie for the first time, really lie, and make it stick. Show us their internal struggle, the physical sensations of deception, and the moment they realize they\'ve succeeded—or failed.',
    category: 'technical',
    mood: ['creative', 'focused'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['character', 'craft', 'tension'],
  },
  {
    id: 'nt3',
    text: 'A boss calls an employee into their corner office. The boss has all the power: the view, the desk, the authority to end this person\'s career. But by the end of the conversation, the employee will walk out with everything, and the boss will have nothing. Write this scene. Show the exact moment the power shifts, and make it feel inevitable in hindsight.',
    category: 'technical',
    mood: ['creative', 'focused'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'write',
    tags: ['reversal', 'craft', 'power'],
  },
  {
    id: 'nt4',
    text: 'A detective enters a suspect\'s apartment for the first time. The suspect isn\'t home. Through describing only what the detective sees—the objects, their arrangement, what\'s present and what\'s conspicuously absent—reveal that this person has a dark secret. Never state what the secret is directly. Let the reader figure it out from the details.',
    category: 'technical',
    mood: ['creative', 'curious'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['visual', 'craft', 'setting'],
  },
  {
    id: 'nt5',
    text: 'Write a conversation between two old friends catching up over coffee. In the first version, they say exactly what they mean—honest, direct, emotionally vulnerable. Then rewrite the exact same conversation, same setting, same topics, but this time both people are hiding something. They never say what they\'re really feeling. Compare how the subtext changes everything.',
    category: 'technical',
    mood: ['creative', 'focused'],
    difficulty: 'advanced',
    estimatedTime: '30 min',
    mode: 'write',
    tags: ['subtext', 'craft', 'dialogue'],
  },
  {
    id: 'nt6',
    text: 'Two colleagues are having lunch together. They\'ve worked side by side for years and genuinely like each other. But during this single meal, something shifts. One of them says or does something that transforms them—in the other\'s eyes—from trusted ally to threat. The betrayal happens in real-time, mid-bite. Write the lunch from the moment they sit down to the moment one of them realizes everything has changed.',
    category: 'technical',
    mood: ['creative', 'energetic'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'write',
    tags: ['reversal', 'craft', 'conflict'],
  },
  {
    id: 'nt7',
    text: 'Someone discovers they\'ve been betrayed by the person they trust most. But you cannot use any dialogue. No spoken words, no texts, no notes. The entire scene must be told through action, body language, objects, and environment. The reader should feel the devastation without anyone saying a word.',
    category: 'technical',
    mood: ['creative', 'focused'],
    difficulty: 'advanced',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['visual', 'craft', 'emotion'],
  },
  {
    id: 'nt8',
    text: 'A person has been working toward a goal for years—maybe a promotion, a relationship, a creative achievement, moving to a dream city. Today they finally got it. They have exactly what they wanted. Write the scene where they get the news, and then the next scene, maybe an hour later, where they realize with creeping horror that they\'ve made a terrible mistake. What did they not see coming?',
    category: 'technical',
    mood: ['creative', 'reflective'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['irony', 'craft', 'character'],
  },
  {
    id: 'nt9',
    text: 'Write a story where a single phrase appears at least four times—but each time it appears, it means something completely different based on context. The phrase could be something simple like "I\'m fine," "It doesn\'t matter," or "I know." Show how the same words can carry grief, then hope, then threat, then acceptance.',
    category: 'technical',
    mood: ['creative', 'focused'],
    difficulty: 'advanced',
    estimatedTime: '25 min',
    mode: 'write',
    tags: ['motif', 'craft', 'layering'],
  },
  {
    id: 'nt10',
    text: 'Someone does something genuinely kind—throws a surprise party, makes an introduction, gives an honest compliment, tries to help. But it backfires spectacularly. The person they were trying to help is now worse off than before, and the relationship might be ruined. Write the aftermath: the awkward conversation, the damage control, the guilt. Explore how good intentions can create wreckage.',
    category: 'technical',
    mood: ['creative', 'reflective'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['irony', 'craft', 'consequence'],
  },
  {
    id: 'nt11',
    text: 'Write an entire story told only through text messages between two people who know each other better than anyone. No narration, no description—just the messages and timestamps. Through their shorthand, their inside jokes, what they don\'t need to explain, and the rhythm of their replies, reveal who these people are to each other. Bonus: include a moment of conflict and resolution.',
    category: 'technical',
    mood: ['creative', 'relaxed'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['dialogue', 'modern', 'intimacy'],
  },
  {
    id: 'nt12',
    text: 'A character discovers evidence that their closest friend has done something terrible—something that would ruin the friend\'s life if it came out. The character has to decide: protect the friend and become complicit, or expose them and lose the relationship forever. Don\'t write the decision. Write the twenty minutes before it, as they weigh everything, remember their history, and try to find a third option that doesn\'t exist.',
    category: 'technical',
    mood: ['reflective', 'focused'],
    difficulty: 'advanced',
    estimatedTime: '30 min',
    mode: 'write',
    tags: ['moral', 'craft', 'dilemma'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CREATIVE CONSTRAINTS (8 prompts) - Specific limitations that spark creativity
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'ncc1',
    text: 'Imagine your pet (or a pet you wish you had) could speak—but only for one hour, and only at midnight. Tonight is the night. They have things to say, questions to ask, and maybe some grievances to air. But they also know the hour will end and they\'ll go back to silent. Write this conversation. What do you each want to say before time runs out?',
    category: 'creative',
    mood: ['creative', 'curious'],
    difficulty: 'beginner',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['fantasy', 'constraint', 'imagination'],
  },
  {
    id: 'ncc2',
    text: 'You must write a story that includes all four of these objects: a dented blue trash can, a red picture frame with the glass cracked, a teddy bear with stuffing falling out of its left arm, and a brass padlock without a key. They must all matter to the plot—they can\'t just appear in the background. Let the objects guide you somewhere unexpected.',
    category: 'creative',
    mood: ['creative', 'energetic'],
    difficulty: 'intermediate',
    estimatedTime: '25 min',
    mode: 'write',
    tags: ['objects', 'constraint', 'creativity'],
  },
  {
    id: 'ncc3',
    text: 'This week held both your biggest mistake and your finest moment—and probably more of each. First, write about something you did this week that you wish you could take back. Don\'t justify it, just describe what happened and how it felt. Then write about something you did that made you proud, even if no one noticed. See what patterns emerge when you hold them side by side.',
    category: 'reflection',
    mood: ['reflective', 'focused'],
    difficulty: 'beginner',
    estimatedTime: '20 min',
    mode: 'reflect',
    tags: ['contrast', 'week', 'balance'],
  },
  {
    id: 'ncc4',
    text: 'You are the first human being to ever set foot on Mars. The landing was rough, but you made it. The hatch opens. You step outside. Describe the first five minutes in detail—what you see, what you hear (or don\'t hear), how your body feels in the gravity, what you smell through the suit, what you think about. This moment has been imagined by billions. Make it real.',
    category: 'creative',
    mood: ['creative', 'excited'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'write',
    tags: ['scifi', 'imagination', 'discovery'],
  },
  {
    id: 'ncc5',
    text: 'There\'s an animal that lives beneath your human exterior. Maybe it\'s been there your whole life, or maybe it changes. Some days it\'s a mouse—cautious, twitchy, ready to bolt. Other days it\'s a cougar—patient, watching, capable of sudden violence. Today, right now, what animal is under your skin? Describe it. What does it want? What does it fear? How does it affect the way you move through the world?',
    category: 'philosophical',
    mood: ['reflective', 'creative'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'both',
    tags: ['metaphor', 'identity', 'animal'],
  },
  {
    id: 'ncc6',
    text: 'Think of something that happened to you recently—a conversation, an event, a change in plans. Write about it twice. First, describe it as if you\'re the most optimistic person alive, finding the silver lining, the growth opportunity, the hidden blessing. Then rewrite it as the most pessimistic version of yourself, seeing the warning signs, the missed chances, the way it confirms your worst fears. Which version feels more honest? Why?',
    category: 'reflection',
    mood: ['reflective', 'curious'],
    difficulty: 'intermediate',
    estimatedTime: '25 min',
    mode: 'both',
    tags: ['perspective', 'contrast', 'reframe'],
  },
  {
    id: 'ncc7',
    text: 'There\'s a particular kind of anger that\'s actually love in disguise—the anger that makes you want to fix something, help someone, change the world. It\'s not bitter or destructive; it\'s fuel. What makes you compassionately angry? What injustice, what unnecessary suffering, what broken system makes you want to stand up and do something? Write about this anger. Where did it come from? What has it made you do?',
    category: 'philosophical',
    mood: ['reflective', 'energetic'],
    difficulty: 'intermediate',
    estimatedTime: '20 min',
    mode: 'reflect',
    tags: ['emotion', 'purpose', 'values'],
  },
  {
    id: 'ncc8',
    text: 'There\'s a state psychologists call "flow"—when you\'re so absorbed in an activity that time dissolves, self-consciousness disappears, and you emerge hours later wondering where the day went. What puts you in that state? It might be creating, solving, playing, moving, building. Describe what it feels like from the inside: how you enter it, what happens to your sense of self, and how jarring it is to come back out.',
    category: 'reflection',
    mood: ['reflective', 'peaceful'],
    difficulty: 'beginner',
    estimatedTime: '20 min',
    mode: 'reflect',
    tags: ['flow', 'passion', 'time'],
  },
]

/**
 * Get nonfiction prompts by category
 */
export function getNonfictionPromptsByCategory(category: PromptCategory): WritingPrompt[] {
  return NONFICTION_PROMPTS.filter((p) => p.category === category)
}

/**
 * Get nonfiction prompts by mood
 */
export function getNonfictionPromptsByMood(mood: MoodState): WritingPrompt[] {
  return NONFICTION_PROMPTS.filter((p) => !p.mood || p.mood.includes(mood))
}

/**
 * Get random nonfiction prompt
 */
export function getRandomNonfictionPrompt(options?: {
  category?: PromptCategory
  mood?: MoodState
}): WritingPrompt {
  let pool = [...NONFICTION_PROMPTS]

  if (options?.category) {
    pool = pool.filter((p) => p.category === options.category)
  }

  if (options?.mood) {
    pool = pool.filter((p) => !p.mood || p.mood.includes(options.mood!))
  }

  if (pool.length === 0) {
    pool = NONFICTION_PROMPTS
  }

  return pool[Math.floor(Math.random() * pool.length)]
}
