/**
 * Writer's Digest Creative Writing Prompts
 * @module lib/prompts/writersDigestPrompts
 *
 * 95 creative writing prompts from Writer's Digest,
 * categorized and adapted for the prompt gallery.
 */

import type { MoodState } from '@/lib/codex/mood'
import type { PromptCategory, PromptMode } from '@/lib/codex/prompts'

export interface WritersDigestPrompt {
  id: string
  text: string
  category: PromptCategory
  mood?: MoodState[]
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  source: 'writers-digest'
  mode: PromptMode
  imagePath?: string
}

/**
 * Writer's Digest prompts - categorized and curated
 */
export const WRITERS_DIGEST_PROMPTS: WritersDigestPrompt[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // REFLECTION - Personal growth, self-discovery, emotions (mode: reflect)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'wd-001', imagePath: '/prompts/wd-001.webp',
    text: 'You have just swallowed your pride and done something you didn\'t want to do. Your friend wants to know why. The two of you are driving around aimlessly. Tell the friend what just happened.',
    category: 'reflection',
    mood: ['reflective'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-002', imagePath: '/prompts/wd-002.webp',
    text: 'A singer leaves a concert series halfway through because of a personal tragedy. She looks at what she\'s about to do and wonders if the audience will forgive her.',
    category: 'reflection',
    mood: ['reflective'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'both',
  },
  {
    id: 'wd-003', imagePath: '/prompts/wd-003.webp',
    text: 'You are an astronaut. Describe your perfect day.',
    category: 'reflection',
    mood: ['creative', 'reflective'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'both',
  },
  {
    id: 'wd-004', imagePath: '/prompts/wd-004.webp',
    text: 'Think of something you are not allowed to do but wish you could. Write about doing it.',
    category: 'reflection',
    mood: ['reflective', 'creative'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-005', imagePath: '/prompts/wd-005.webp',
    text: 'Nobody knows what went on behind closed doors. Tell them.',
    category: 'reflection',
    mood: ['reflective'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'both',
  },
  {
    id: 'wd-006', imagePath: '/prompts/wd-006.webp',
    text: 'A woman has been searching for her birth parents. After years of dead ends, she gets a lead. She pulls into the driveway of a trailer with Christmas lights up all year round, gets out of her car, and knocks on the door.',
    category: 'reflection',
    mood: ['reflective'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-007', imagePath: '/prompts/wd-007.webp',
    text: 'Describe what you never want to forget about a friend.',
    category: 'reflection',
    mood: ['reflective', 'relaxed'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-008', imagePath: '/prompts/wd-008.webp',
    text: 'This happened years ago, before we knew any of it mattered.',
    category: 'reflection',
    mood: ['reflective'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'both',
  },
  {
    id: 'wd-009', imagePath: '/prompts/wd-009.webp',
    text: 'Describe the last time you felt genuinely grateful—what triggered it and how did it change your day?',
    category: 'reflection',
    mood: ['reflective', 'relaxed'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-010', imagePath: '/prompts/wd-010.webp',
    text: 'She thought about the last thing her dad ever said to her, a simple statement that grew in power every year.',
    category: 'reflection',
    mood: ['reflective'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'both',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CREATIVE - Story starters, character sketches, scenarios (mode: write)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'wd-012', imagePath: '/prompts/wd-012.webp',
    text: 'A little girl is terrified of the stuffed rabbit perched on her dresser. At night, she swears it moves closer and closer to the edge.',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-013', imagePath: '/prompts/wd-013.webp',
    text: 'After falling asleep on the subway, you wake up somewhere you don\'t recognize. Explore.',
    category: 'creative',
    mood: ['creative', 'curious'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-014', imagePath: '/prompts/wd-014.webp',
    text: 'A superhero wants to retire, but crime in the city is at an all-time high.',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-015', imagePath: '/prompts/wd-015.webp',
    text: 'Your character is digging in their garden and finds a fist-sized, perfectly round stone. Upon investigation, they discover the stone is not only magnetic, but has a strange attraction to their blood.',
    category: 'creative',
    mood: ['creative', 'curious'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-016', imagePath: '/prompts/wd-016.webp',
    text: 'The magician announces he will perform one final trick, then promptly drops dead.',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-017', imagePath: '/prompts/wd-017.webp',
    text: 'In the middle of dinner, your wife says, "I need you to shave your beard." You say no. She picks up a kitchen knife.',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-019', imagePath: '/prompts/wd-019.webp',
    text: 'Two kids find a message in a bottle at the beach. They follow the map inside.',
    category: 'creative',
    mood: ['creative', 'curious'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-020', imagePath: '/prompts/wd-020.webp',
    text: 'A woman bumps into a man while walking across the street, causing him to drop a briefcase. The man is very angry, even though the woman apologizes. What happens when she sees him again later in the day?',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-021', imagePath: '/prompts/wd-021.webp',
    text: 'A time-traveler visits the set of a popular sitcom in the 1990s. What happens when they try to fit in?',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-022', imagePath: '/prompts/wd-022.webp',
    text: 'A teenager who is into the wrong crowd becomes a foster big sister.',
    category: 'creative',
    mood: ['creative', 'reflective'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-023', imagePath: '/prompts/wd-023.webp',
    text: 'Write a story that ends with this sentence: "And then he remembered, in a rush, what he\'d done."',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-024', imagePath: '/prompts/wd-024.webp',
    text: 'An elderly widow prepares to go back to the workforce after 50 years.',
    category: 'creative',
    mood: ['creative', 'reflective'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-025', imagePath: '/prompts/wd-025.webp',
    text: 'Her mother told her she\'d never amount to anything. She was determined to prove her wrong.',
    category: 'creative',
    mood: ['creative', 'energetic'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-026', imagePath: '/prompts/wd-026.webp',
    text: 'An old man in hospice care regrets never making amends with his children.',
    category: 'creative',
    mood: ['reflective'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-027', imagePath: '/prompts/wd-027.webp',
    text: 'That morning, Jessica fed her cat, grabbed her backpack, and headed out to change the world.',
    category: 'creative',
    mood: ['creative', 'energetic'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-028', imagePath: '/prompts/wd-028.webp',
    text: 'The dog\'s breakfast was cat food, and the cat\'s breakfast was freedom.',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-029', imagePath: '/prompts/wd-029.webp',
    text: 'A villain gives a victim one chance to go free, if she can answer a riddle.',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // EXPLORATION - Discovery, imagination, what-if scenarios (mode: write)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'wd-031', imagePath: '/prompts/wd-031.webp',
    text: 'A woman is alone in the middle of an empty concert hall. What does she do there?',
    category: 'exploration',
    mood: ['curious', 'creative'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-032', imagePath: '/prompts/wd-032.webp',
    text: 'A graduate student realizes her professor has been taking credit for her work.',
    category: 'exploration',
    mood: ['curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-033', imagePath: '/prompts/wd-033.webp',
    text: 'There\'s a strange tapping noise on the window. It\'s too high up to be a tree branch.',
    category: 'exploration',
    mood: ['curious', 'creative'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-034', imagePath: '/prompts/wd-034.webp',
    text: 'Think of a dish your parents made that didn\'t turn out correctly. Write about it.',
    category: 'exploration',
    mood: ['curious', 'reflective'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-035', imagePath: '/prompts/wd-035.webp',
    text: 'A woman signs up for a dance class for the first time in 30 years.',
    category: 'exploration',
    mood: ['curious', 'energetic'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-037', imagePath: '/prompts/wd-037.webp',
    text: 'A man rescues an angel from the crosswalk.',
    category: 'exploration',
    mood: ['creative', 'curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-038', imagePath: '/prompts/wd-038.webp',
    text: 'There\'s a rumor that your daughter isn\'t actually yours.',
    category: 'exploration',
    mood: ['curious'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-039', imagePath: '/prompts/wd-039.webp',
    text: 'An unsolved mystery that fascinates you. Explore what might have happened.',
    category: 'exploration',
    mood: ['curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-040', imagePath: '/prompts/wd-040.webp',
    text: 'Inside the mysterious shop, everything has a price tag—even things that shouldn\'t.',
    category: 'exploration',
    mood: ['creative', 'curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PERSONAL - Memories, relationships, life experiences (mode: reflect)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'wd-041', imagePath: '/prompts/wd-041.webp',
    text: 'We drove past my old house on the way home and I thought about everything that had changed.',
    category: 'personal',
    mood: ['reflective'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-042', imagePath: '/prompts/wd-042.webp',
    text: 'A bride who has been planning her wedding for months catches her fiancé with one of the bridesmaids.',
    category: 'personal',
    mood: ['reflective'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-043', imagePath: '/prompts/wd-043.webp',
    text: 'A child writes a letter to Santa Claus, but it gets intercepted by someone else.',
    category: 'personal',
    mood: ['creative'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-044', imagePath: '/prompts/wd-044.webp',
    text: 'A waiter is the main character but the story is about the married couple sitting at Table 6.',
    category: 'personal',
    mood: ['curious', 'creative'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-045', imagePath: '/prompts/wd-045.webp',
    text: 'A man on his deathbed confesses a lie he told his family years ago.',
    category: 'personal',
    mood: ['reflective'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-046', imagePath: '/prompts/wd-046.webp',
    text: 'A teenager discovers old love letters belonging to her grandmother.',
    category: 'personal',
    mood: ['curious', 'reflective'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-047', imagePath: '/prompts/wd-047.webp',
    text: 'Write about the first time you felt truly independent.',
    category: 'personal',
    mood: ['reflective', 'energetic'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-048', imagePath: '/prompts/wd-048.webp',
    text: 'A family tradition that means more than anyone realizes.',
    category: 'personal',
    mood: ['reflective', 'relaxed'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-049', imagePath: '/prompts/wd-049.webp',
    text: 'Two strangers are snowed in at an airport terminal over Christmas.',
    category: 'personal',
    mood: ['creative', 'relaxed'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-050', imagePath: '/prompts/wd-050.webp',
    text: 'The gift I never gave, but should have.',
    category: 'personal',
    mood: ['reflective'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'reflect',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PHILOSOPHICAL - Deep questions, moral dilemmas (mode: both)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'wd-051', imagePath: '/prompts/wd-051.webp',
    text: 'Your character learns the world will end in three months. What do they do?',
    category: 'philosophical',
    mood: ['reflective', 'curious'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-052', imagePath: '/prompts/wd-052.webp',
    text: 'A detective realizes the criminal they\'ve been chasing is actually trying to do good.',
    category: 'philosophical',
    mood: ['curious', 'reflective'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-053', imagePath: '/prompts/wd-053.webp',
    text: 'Two people with opposing beliefs are stuck together in an elevator.',
    category: 'philosophical',
    mood: ['curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-054', imagePath: '/prompts/wd-054.webp',
    text: 'What would you do if you found out your best friend committed a serious crime?',
    category: 'philosophical',
    mood: ['reflective'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'both',
  },
  {
    id: 'wd-055', imagePath: '/prompts/wd-055.webp',
    text: 'The one thing that money can never buy, but everyone desperately wants.',
    category: 'philosophical',
    mood: ['reflective', 'curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'both',
  },
  {
    id: 'wd-056', imagePath: '/prompts/wd-056.webp',
    text: 'A character must choose between saving one person they love or five strangers.',
    category: 'philosophical',
    mood: ['reflective'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-057', imagePath: '/prompts/wd-057.webp',
    text: 'Write about a lie that turned out to be the kindest thing someone ever did.',
    category: 'philosophical',
    mood: ['reflective', 'curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'both',
  },
  {
    id: 'wd-058', imagePath: '/prompts/wd-058.webp',
    text: 'What does home mean when you\'ve never had one?',
    category: 'philosophical',
    mood: ['reflective'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'both',
  },
  {
    id: 'wd-059', imagePath: '/prompts/wd-059.webp',
    text: 'If you could erase one memory, would you? Which one and why?',
    category: 'philosophical',
    mood: ['reflective'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-060', imagePath: '/prompts/wd-060.webp',
    text: 'The truth is a heavy thing. Sometimes lies are lighter.',
    category: 'philosophical',
    mood: ['reflective', 'curious'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'both',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PRACTICAL - Situations, challenges, real-world scenarios (mode: write)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'wd-061', imagePath: '/prompts/wd-061.webp',
    text: 'Someone who just quit their job gets into an elevator with their former boss.',
    category: 'practical',
    mood: ['focused'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-062', imagePath: '/prompts/wd-062.webp',
    text: 'A real estate agent sells a house that may be haunted.',
    category: 'practical',
    mood: ['creative'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-063', imagePath: '/prompts/wd-063.webp',
    text: 'Your character gets the job of their dreams but it requires them to move across the country.',
    category: 'practical',
    mood: ['focused', 'reflective'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-064', imagePath: '/prompts/wd-064.webp',
    text: 'Write about a time when technology failed at the worst possible moment.',
    category: 'practical',
    mood: ['focused'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'both',
  },
  {
    id: 'wd-065', imagePath: '/prompts/wd-065.webp',
    text: 'A character discovers their neighbor is living a secret double life.',
    category: 'practical',
    mood: ['curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-066', imagePath: '/prompts/wd-066.webp',
    text: 'The first day at a new school, but you\'re the teacher.',
    category: 'practical',
    mood: ['focused', 'energetic'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-067', imagePath: '/prompts/wd-067.webp',
    text: 'A doctor has to tell a patient bad news, but the patient has their own news to share first.',
    category: 'practical',
    mood: ['reflective'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-068', imagePath: '/prompts/wd-068.webp',
    text: 'The interview was going well until they asked the one question I dreaded.',
    category: 'practical',
    mood: ['focused'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'both',
  },
  {
    id: 'wd-069', imagePath: '/prompts/wd-069.webp',
    text: 'A person prepares to host a dinner party, but nothing goes according to plan.',
    category: 'practical',
    mood: ['creative', 'energetic'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-070', imagePath: '/prompts/wd-070.webp',
    text: 'You find a wallet on the street with $500 in cash and a driver\'s license.',
    category: 'practical',
    mood: ['reflective', 'focused'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'both',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LEARNING - Insights, discoveries, growth moments (mode: mostly reflect)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'wd-071', imagePath: '/prompts/wd-071.webp',
    text: 'A skill you thought was useless turned out to save the day.',
    category: 'learning',
    mood: ['curious', 'focused'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'both',
  },
  {
    id: 'wd-072', imagePath: '/prompts/wd-072.webp',
    text: 'Something you learned the hard way that you wish someone had told you.',
    category: 'learning',
    mood: ['reflective'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-073', imagePath: '/prompts/wd-073.webp',
    text: 'A book that changed how you see the world. Explain its impact.',
    category: 'learning',
    mood: ['reflective', 'curious'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-074', imagePath: '/prompts/wd-074.webp',
    text: 'The most important lesson a stranger ever taught you.',
    category: 'learning',
    mood: ['reflective'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-075', imagePath: '/prompts/wd-075.webp',
    text: 'Describe a moment when you realized you were completely wrong about something.',
    category: 'learning',
    mood: ['reflective', 'curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-076', imagePath: '/prompts/wd-076.webp',
    text: 'Your character discovers a talent they never knew they had.',
    category: 'learning',
    mood: ['creative', 'energetic'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-077', imagePath: '/prompts/wd-077.webp',
    text: 'The worst advice you ever received, and what you learned from ignoring it.',
    category: 'learning',
    mood: ['reflective'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-078', imagePath: '/prompts/wd-078.webp',
    text: 'A failure that led to something better.',
    category: 'learning',
    mood: ['reflective', 'energetic'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'both',
  },
  {
    id: 'wd-079', imagePath: '/prompts/wd-079.webp',
    text: 'Something you believed as a child that you now know isn\'t true.',
    category: 'learning',
    mood: ['reflective', 'curious'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'reflect',
  },
  {
    id: 'wd-080', imagePath: '/prompts/wd-080.webp',
    text: 'The moment you realized you were growing up.',
    category: 'learning',
    mood: ['reflective'],
    difficulty: 'beginner',
    source: 'writers-digest',
    mode: 'reflect',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TECHNICAL - Problem-solving, analytical scenarios (mode: write)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'wd-081', imagePath: '/prompts/wd-081.webp',
    text: 'A scientist makes a breakthrough but realizes the implications could be dangerous.',
    category: 'technical',
    mood: ['focused', 'curious'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-082', imagePath: '/prompts/wd-082.webp',
    text: 'Describe a system that works perfectly in theory but fails in practice.',
    category: 'technical',
    mood: ['focused'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'both',
  },
  {
    id: 'wd-083', imagePath: '/prompts/wd-083.webp',
    text: 'An engineer discovers a flaw in a structure that\'s already been built.',
    category: 'technical',
    mood: ['focused'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-084', imagePath: '/prompts/wd-084.webp',
    text: 'The AI assistant started giving strange recommendations. At first, I thought it was a bug.',
    category: 'technical',
    mood: ['curious', 'focused'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-085', imagePath: '/prompts/wd-085.webp',
    text: 'Document a process you created to solve a recurring problem.',
    category: 'technical',
    mood: ['focused'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MORE CREATIVE - Additional story starters (mode: write)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'wd-086', imagePath: '/prompts/wd-086.webp',
    text: 'All the flowers in the garden bloomed at once, even the ones that were dead.',
    category: 'creative',
    mood: ['creative', 'curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-087', imagePath: '/prompts/wd-087.webp',
    text: 'A museum security guard notices that one of the paintings has changed overnight.',
    category: 'creative',
    mood: ['creative', 'curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-088', imagePath: '/prompts/wd-088.webp',
    text: 'Your character wakes up to discover everyone in the world has vanished except them.',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-089', imagePath: '/prompts/wd-089.webp',
    text: 'A librarian discovers a book that writes itself as you read it.',
    category: 'creative',
    mood: ['creative', 'curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-090', imagePath: '/prompts/wd-090.webp',
    text: 'Two people meet for the first time, but one of them remembers their future together.',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-091', imagePath: '/prompts/wd-091.webp',
    text: 'The clock struck midnight, but time didn\'t move forward.',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-092', imagePath: '/prompts/wd-092.webp',
    text: 'A character receives a package addressed to the person they used to be.',
    category: 'creative',
    mood: ['creative', 'reflective'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-093', imagePath: '/prompts/wd-093.webp',
    text: 'Every night at 3 AM, the radio turns on by itself and plays the same song.',
    category: 'creative',
    mood: ['creative', 'curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-094', imagePath: '/prompts/wd-094.webp',
    text: 'A fortune teller refuses to reveal what she sees in someone\'s future.',
    category: 'creative',
    mood: ['creative'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-095', imagePath: '/prompts/wd-095.webp',
    text: 'The last tree on Earth tells its story.',
    category: 'creative',
    mood: ['creative', 'reflective'],
    difficulty: 'advanced',
    source: 'writers-digest',
    mode: 'write',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FINAL SET - Mixed categories (mode: mixed)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'wd-096', imagePath: '/prompts/wd-096.webp',
    text: 'A street performer has a secret that could change everything.',
    category: 'creative',
    mood: ['creative', 'curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-097', imagePath: '/prompts/wd-097.webp',
    text: 'Write about the moment right before everything changed.',
    category: 'reflection',
    mood: ['reflective'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'both',
  },
  {
    id: 'wd-098', imagePath: '/prompts/wd-098.webp',
    text: 'A character finds a note in their own handwriting that they don\'t remember writing.',
    category: 'creative',
    mood: ['creative', 'curious'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'write',
  },
  {
    id: 'wd-099', imagePath: '/prompts/wd-099.webp',
    text: 'The last conversation you had that truly mattered.',
    category: 'personal',
    mood: ['reflective'],
    difficulty: 'intermediate',
    source: 'writers-digest',
    mode: 'reflect',
  },
]

/**
 * Get all Writer's Digest prompts
 */
export function getWritersDigestPrompts(): WritersDigestPrompt[] {
  return WRITERS_DIGEST_PROMPTS
}

/**
 * Get Writer's Digest prompts by category
 */
export function getWritersDigestPromptsByCategory(
  category: PromptCategory
): WritersDigestPrompt[] {
  return WRITERS_DIGEST_PROMPTS.filter((p) => p.category === category)
}

/**
 * Get Writer's Digest prompts by mood
 */
export function getWritersDigestPromptsByMood(
  mood: MoodState
): WritersDigestPrompt[] {
  return WRITERS_DIGEST_PROMPTS.filter(
    (p) => !p.mood || p.mood.includes(mood)
  )
}
