packages:
  - "registry/curated/auth"
  - "registry/curated/provenance/anchor-providers"
  - "registry/curated/provenance/wunderland-tip-ingestion"
  - "registry/curated/research/web-search"
  - "registry/curated/research/web-browser"
  - "registry/curated/integrations/telegram"
  - "registry/curated/communications/telegram-bot"
  - "registry/curated/system/cli-executor"
  - "registry/curated/media/giphy"
  - "registry/curated/media/image-search"
  - "registry/curated/media/voice-synthesis"
  - "registry/curated/research/news-search"
  - "registry/curated/channels/telegram"
  - "registry/curated/channels/whatsapp"
  - "registry/curated/channels/discord"
  - "registry/curated/channels/slack"
  - "registry/curated/channels/webchat"
  - "registry/curated/voice/twilio"
  - "registry/curated/voice/telnyx"
  - "registry/curated/voice/plivo"
  - "registry/curated/productivity/google-calendar"
  - "registry/curated/productivity/gmail"
